// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/snow/consensus/snowman (interfaces: Block)
//
// Generated by this command:
//
//	mockgen -package=snowmanmock -destination=snowmanmock/block.go -mock_names=Block=Block . Block
//

// Package snowmanmock is a generated GoMock package.
package snowmanmock

import (
	context "context"
	time "time"

	ids "github.com/ava-labs/avalanchego/ids"
	gomock "go.uber.org/mock/gomock"
)

// Block is a mock of Block interface.
type Block struct {
	ctrl     *gomock.Controller
	recorder *BlockMockRecorder
	isgomock struct{}
}

// BlockMockRecorder is the mock recorder for Block.
type BlockMockRecorder struct {
	mock *Block
}

// NewBlock creates a new mock instance.
func NewBlock(ctrl *gomock.Controller) *Block { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Block) EXPECT() *BlockMockRecorder {
	_ = "STUB: not implemented"

	// Accept mocks base method.
	return nil
}

func (m *Block) Accept(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Accept indicates an expected call of Accept.
func (mr *BlockMockRecorder) Accept(arg0 any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// Bytes mocks base method.
func (m *Block) Bytes() []byte { _ = "STUB: not implemented"; return nil }

// Bytes indicates an expected call of Bytes.
func (mr *BlockMockRecorder) Bytes() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Height mocks base method.
func (m *Block) Height() uint64 { _ = "STUB: not implemented"; return 0 }

// Height indicates an expected call of Height.
func (mr *BlockMockRecorder) Height() *gomock.Call { _ = "STUB: not implemented"; return nil }

// ID mocks base method.
func (m *Block) ID() ids.ID { _ = "STUB: not implemented"; return *new(ids.ID) }

// ID indicates an expected call of ID.
func (mr *BlockMockRecorder) ID() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Parent mocks base method.
func (m *Block) Parent() ids.ID { _ = "STUB: not implemented"; return *new(ids.ID) }

// Parent indicates an expected call of Parent.
func (mr *BlockMockRecorder) Parent() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Reject mocks base method.
func (m *Block) Reject(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Reject indicates an expected call of Reject.
func (mr *BlockMockRecorder) Reject(arg0 any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// Timestamp mocks base method.
func (m *Block) Timestamp() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

// Timestamp indicates an expected call of Timestamp.
func (mr *BlockMockRecorder) Timestamp() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Verify mocks base method.
func (m *Block) Verify(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Verify indicates an expected call of Verify.
func (mr *BlockMockRecorder) Verify(arg0 any) *gomock.Call { _ = "STUB: not implemented"; return nil }
