// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/vms/avm/txs (interfaces: UnsignedTx)
//
// Generated by this command:
//
//	mockgen -package=txsmock -destination=txsmock/tx.go -mock_names=UnsignedTx=UnsignedTx . UnsignedTx
//

// Package txsmock is a generated GoMock package.
package txsmock

import (
	ids "github.com/ava-labs/avalanchego/ids"
	snow "github.com/ava-labs/avalanchego/snow"
	set "github.com/ava-labs/avalanchego/utils/set"
	txs "github.com/ava-labs/avalanchego/vms/avm/txs"
	avax "github.com/ava-labs/avalanchego/vms/components/avax"
	gomock "go.uber.org/mock/gomock"
)

// UnsignedTx is a mock of UnsignedTx interface.
type UnsignedTx struct {
	ctrl     *gomock.Controller
	recorder *UnsignedTxMockRecorder
	isgomock struct{}
}

// UnsignedTxMockRecorder is the mock recorder for UnsignedTx.
type UnsignedTxMockRecorder struct {
	mock *UnsignedTx
}

// NewUnsignedTx creates a new mock instance.
func NewUnsignedTx(ctrl *gomock.Controller) *UnsignedTx { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UnsignedTx) EXPECT() *UnsignedTxMockRecorder {
	_ = "STUB: not implemented"

	// Bytes mocks base method.
	return nil
}

func (m *UnsignedTx) Bytes() []byte { _ = "STUB: not implemented"; return nil }

// Bytes indicates an expected call of Bytes.
func (mr *UnsignedTxMockRecorder) Bytes() *gomock.Call { _ = "STUB: not implemented"; return nil }

// InitCtx mocks base method.
func (m *UnsignedTx) InitCtx(ctx *snow.Context) { _ = "STUB: not implemented"; return }

// InitCtx indicates an expected call of InitCtx.
func (mr *UnsignedTxMockRecorder) InitCtx(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// InputIDs mocks base method.
func (m *UnsignedTx) InputIDs() set.Set[ids.ID] { _ = "STUB: not implemented"; return nil }

// InputIDs indicates an expected call of InputIDs.
func (mr *UnsignedTxMockRecorder) InputIDs() *gomock.Call { _ = "STUB: not implemented"; return nil }

// InputUTXOs mocks base method.
func (m *UnsignedTx) InputUTXOs() []*avax.UTXOID { _ = "STUB: not implemented"; return nil }

// InputUTXOs indicates an expected call of InputUTXOs.
func (mr *UnsignedTxMockRecorder) InputUTXOs() *gomock.Call { _ = "STUB: not implemented"; return nil }

// NumCredentials mocks base method.
func (m *UnsignedTx) NumCredentials() int { _ = "STUB: not implemented"; return 0 }

// NumCredentials indicates an expected call of NumCredentials.
func (mr *UnsignedTxMockRecorder) NumCredentials() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetBytes mocks base method.
func (m *UnsignedTx) SetBytes(unsignedBytes []byte) { _ = "STUB: not implemented"; return }

// SetBytes indicates an expected call of SetBytes.
func (mr *UnsignedTxMockRecorder) SetBytes(unsignedBytes any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Visit mocks base method.
func (m *UnsignedTx) Visit(visitor txs.Visitor) error { _ = "STUB: not implemented"; return nil }

// Visit indicates an expected call of Visit.
func (mr *UnsignedTxMockRecorder) Visit(visitor any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
