// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/utils/hashing (interfaces: Hasher)
//
// Generated by this command:
//
//	mockgen -package=hashingmock -destination=hashingmock/hasher.go -mock_names=Hasher=Hasher . Hasher
//

// Package hashingmock is a generated GoMock package.
package hashingmock

import (
	gomock "go.uber.org/mock/gomock"
)

// Hasher is a mock of Hasher interface.
type Hasher struct {
	ctrl     *gomock.Controller
	recorder *HasherMockRecorder
	isgomock struct{}
}

// HasherMockRecorder is the mock recorder for Hasher.
type HasherMockRecorder struct {
	mock *Hasher
}

// NewHasher creates a new mock instance.
func NewHasher(ctrl *gomock.Controller) *Hasher { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Hasher) EXPECT() *HasherMockRecorder {
	_ = "STUB: not implemented"

	// Hash mocks base method.
	return nil
}

func (m *Hasher) Hash(arg0 []byte) uint64 { _ = "STUB: not implemented"; return 0 }

// Hash indicates an expected call of Hash.
func (mr *HasherMockRecorder) Hash(arg0 any) *gomock.Call { _ = "STUB: not implemented"; return nil }
