// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: rpcdb/rpcdb.proto

package rpcdb

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error int32

const (
	// ERROR_UNSPECIFIED is used to indicate that no error occurred.
	Error_ERROR_UNSPECIFIED Error = 0
	Error_ERROR_CLOSED      Error = 1
	Error_ERROR_NOT_FOUND   Error = 2
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0: "ERROR_UNSPECIFIED",
		1: "ERROR_CLOSED",
		2: "ERROR_NOT_FOUND",
	}
	Error_value = map[string]int32{
		"ERROR_UNSPECIFIED": 0,
		"ERROR_CLOSED":      1,
		"ERROR_NOT_FOUND":   2,
	}
)

func (x Error) Enum() *Error { _ = "STUB: not implemented"; return nil }

func (x Error) String() string { _ = "STUB: not implemented"; return "" }

func (Error) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (Error) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x Error) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type HasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *HasRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*HasRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *HasRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use HasRequest.ProtoReflect.Descriptor instead.
func (*HasRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *HasRequest) GetKey() []byte { _ = "STUB: not implemented"; return nil }

type HasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Has           bool                   `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
	Err           Error                  `protobuf:"varint,2,opt,name=err,proto3,enum=rpcdb.Error" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *HasResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*HasResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *HasResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use HasResponse.ProtoReflect.Descriptor instead.
func (*HasResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *HasResponse) GetHas() bool { _ = "STUB: not implemented"; return false }

func (x *HasResponse) GetErr() Error { _ = "STUB: not implemented"; return *new(Error) }

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *GetRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*GetRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *GetRequest) GetKey() []byte { _ = "STUB: not implemented"; return nil }

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Err           Error                  `protobuf:"varint,2,opt,name=err,proto3,enum=rpcdb.Error" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *GetResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*GetResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *GetResponse) GetValue() []byte { _ = "STUB: not implemented"; return nil }

func (x *GetResponse) GetErr() Error { _ = "STUB: not implemented"; return *new(Error) }

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *PutRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*PutRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PutRequest) GetKey() []byte { _ = "STUB: not implemented"; return nil }

func (x *PutRequest) GetValue() []byte { _ = "STUB: not implemented"; return nil }

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           Error                  `protobuf:"varint,1,opt,name=err,proto3,enum=rpcdb.Error" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *PutResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*PutResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PutResponse) GetErr() Error { _ = "STUB: not implemented"; return *new(Error) }

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *DeleteRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*DeleteRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *DeleteRequest) GetKey() []byte { _ = "STUB: not implemented"; return nil }

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           Error                  `protobuf:"varint,1,opt,name=err,proto3,enum=rpcdb.Error" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *DeleteResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*DeleteResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *DeleteResponse) GetErr() Error { _ = "STUB: not implemented"; return *new(Error) }

type CompactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         []byte                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Limit         []byte                 `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *CompactRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*CompactRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *CompactRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use CompactRequest.ProtoReflect.Descriptor instead.
func (*CompactRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *CompactRequest) GetStart() []byte { _ = "STUB: not implemented"; return nil }

func (x *CompactRequest) GetLimit() []byte { _ = "STUB: not implemented"; return nil }

type CompactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           Error                  `protobuf:"varint,1,opt,name=err,proto3,enum=rpcdb.Error" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *CompactResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*CompactResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *CompactResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use CompactResponse.ProtoReflect.Descriptor instead.
func (*CompactResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *CompactResponse) GetErr() Error { _ = "STUB: not implemented"; return *new(Error) }

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *CloseRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*CloseRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           Error                  `protobuf:"varint,1,opt,name=err,proto3,enum=rpcdb.Error" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *CloseResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*CloseResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *CloseResponse) GetErr() Error { _ = "STUB: not implemented"; return *new(Error) }

type WriteBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Puts          []*PutRequest          `protobuf:"bytes,1,rep,name=puts,proto3" json:"puts,omitempty"`
	Deletes       []*DeleteRequest       `protobuf:"bytes,2,rep,name=deletes,proto3" json:"deletes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBatchRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *WriteBatchRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*WriteBatchRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *WriteBatchRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use WriteBatchRequest.ProtoReflect.Descriptor instead.
func (*WriteBatchRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *WriteBatchRequest) GetPuts() []*PutRequest { _ = "STUB: not implemented"; return nil }

func (x *WriteBatchRequest) GetDeletes() []*DeleteRequest { _ = "STUB: not implemented"; return nil }

type WriteBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           Error                  `protobuf:"varint,1,opt,name=err,proto3,enum=rpcdb.Error" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteBatchResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *WriteBatchResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*WriteBatchResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *WriteBatchResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use WriteBatchResponse.ProtoReflect.Descriptor instead.
func (*WriteBatchResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *WriteBatchResponse) GetErr() Error { _ = "STUB: not implemented"; return *new(Error) }

type NewIteratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewIteratorRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *NewIteratorRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*NewIteratorRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *NewIteratorRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use NewIteratorRequest.ProtoReflect.Descriptor instead.
func (*NewIteratorRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type NewIteratorWithStartAndPrefixRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         []byte                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Prefix        []byte                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewIteratorWithStartAndPrefixRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *NewIteratorWithStartAndPrefixRequest) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (*NewIteratorWithStartAndPrefixRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *NewIteratorWithStartAndPrefixRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use NewIteratorWithStartAndPrefixRequest.ProtoReflect.Descriptor instead.
func (*NewIteratorWithStartAndPrefixRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *NewIteratorWithStartAndPrefixRequest) GetStart() []byte {
	_ = "STUB: not implemented"
	return nil
}

func (x *NewIteratorWithStartAndPrefixRequest) GetPrefix() []byte {
	_ = "STUB: not implemented"
	return nil
}

type NewIteratorWithStartAndPrefixResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewIteratorWithStartAndPrefixResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *NewIteratorWithStartAndPrefixResponse) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (*NewIteratorWithStartAndPrefixResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *NewIteratorWithStartAndPrefixResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use NewIteratorWithStartAndPrefixResponse.ProtoReflect.Descriptor instead.
func (*NewIteratorWithStartAndPrefixResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *NewIteratorWithStartAndPrefixResponse) GetId() uint64 { _ = "STUB: not implemented"; return 0 }

type IteratorNextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IteratorNextRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *IteratorNextRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*IteratorNextRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *IteratorNextRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use IteratorNextRequest.ProtoReflect.Descriptor instead.
func (*IteratorNextRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *IteratorNextRequest) GetId() uint64 { _ = "STUB: not implemented"; return 0 }

type IteratorNextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*PutRequest          `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IteratorNextResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *IteratorNextResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*IteratorNextResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *IteratorNextResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use IteratorNextResponse.ProtoReflect.Descriptor instead.
func (*IteratorNextResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *IteratorNextResponse) GetData() []*PutRequest { _ = "STUB: not implemented"; return nil }

type IteratorErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IteratorErrorRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *IteratorErrorRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*IteratorErrorRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *IteratorErrorRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use IteratorErrorRequest.ProtoReflect.Descriptor instead.
func (*IteratorErrorRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *IteratorErrorRequest) GetId() uint64 { _ = "STUB: not implemented"; return 0 }

type IteratorErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           Error                  `protobuf:"varint,1,opt,name=err,proto3,enum=rpcdb.Error" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IteratorErrorResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *IteratorErrorResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*IteratorErrorResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *IteratorErrorResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use IteratorErrorResponse.ProtoReflect.Descriptor instead.
func (*IteratorErrorResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *IteratorErrorResponse) GetErr() Error { _ = "STUB: not implemented"; return *new(Error) }

type IteratorReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IteratorReleaseRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *IteratorReleaseRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*IteratorReleaseRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *IteratorReleaseRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use IteratorReleaseRequest.ProtoReflect.Descriptor instead.
func (*IteratorReleaseRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *IteratorReleaseRequest) GetId() uint64 { _ = "STUB: not implemented"; return 0 }

type IteratorReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           Error                  `protobuf:"varint,1,opt,name=err,proto3,enum=rpcdb.Error" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IteratorReleaseResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *IteratorReleaseResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*IteratorReleaseResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *IteratorReleaseResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use IteratorReleaseResponse.ProtoReflect.Descriptor instead.
func (*IteratorReleaseResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *IteratorReleaseResponse) GetErr() Error { _ = "STUB: not implemented"; return *new(Error) }

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       []byte                 `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *HealthCheckResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*HealthCheckResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *HealthCheckResponse) GetDetails() []byte { _ = "STUB: not implemented"; return nil }

var File_rpcdb_rpcdb_proto protoreflect.FileDescriptor

const file_rpcdb_rpcdb_proto_rawDesc = "" +
	"\n" +
	"\x11rpcdb/rpcdb.proto\x12\x05rpcdb\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n" +
	"\n" +
	"HasRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"?\n" +
	"\vHasResponse\x12\x10\n" +
	"\x03has\x18\x01 \x01(\bR\x03has\x12\x1e\n" +
	"\x03err\x18\x02 \x01(\x0e2\f.rpcdb.ErrorR\x03err\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"C\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x1e\n" +
	"\x03err\x18\x02 \x01(\x0e2\f.rpcdb.ErrorR\x03err\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"-\n" +
	"\vPutResponse\x12\x1e\n" +
	"\x03err\x18\x01 \x01(\x0e2\f.rpcdb.ErrorR\x03err\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"0\n" +
	"\x0eDeleteResponse\x12\x1e\n" +
	"\x03err\x18\x01 \x01(\x0e2\f.rpcdb.ErrorR\x03err\"<\n" +
	"\x0eCompactRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\fR\x05start\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\fR\x05limit\"1\n" +
	"\x0fCompactResponse\x12\x1e\n" +
	"\x03err\x18\x01 \x01(\x0e2\f.rpcdb.ErrorR\x03err\"\x0e\n" +
	"\fCloseRequest\"/\n" +
	"\rCloseResponse\x12\x1e\n" +
	"\x03err\x18\x01 \x01(\x0e2\f.rpcdb.ErrorR\x03err\"j\n" +
	"\x11WriteBatchRequest\x12%\n" +
	"\x04puts\x18\x01 \x03(\v2\x11.rpcdb.PutRequestR\x04puts\x12.\n" +
	"\adeletes\x18\x02 \x03(\v2\x14.rpcdb.DeleteRequestR\adeletes\"4\n" +
	"\x12WriteBatchResponse\x12\x1e\n" +
	"\x03err\x18\x01 \x01(\x0e2\f.rpcdb.ErrorR\x03err\"\x14\n" +
	"\x12NewIteratorRequest\"T\n" +
	"$NewIteratorWithStartAndPrefixRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\fR\x05start\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\fR\x06prefix\"7\n" +
	"%NewIteratorWithStartAndPrefixResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"%\n" +
	"\x13IteratorNextRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"=\n" +
	"\x14IteratorNextResponse\x12%\n" +
	"\x04data\x18\x01 \x03(\v2\x11.rpcdb.PutRequestR\x04data\"&\n" +
	"\x14IteratorErrorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"7\n" +
	"\x15IteratorErrorResponse\x12\x1e\n" +
	"\x03err\x18\x01 \x01(\x0e2\f.rpcdb.ErrorR\x03err\"(\n" +
	"\x16IteratorReleaseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"9\n" +
	"\x17IteratorReleaseResponse\x12\x1e\n" +
	"\x03err\x18\x01 \x01(\x0e2\f.rpcdb.ErrorR\x03err\"/\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\adetails\x18\x01 \x01(\fR\adetails*E\n" +
	"\x05Error\x12\x15\n" +
	"\x11ERROR_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fERROR_CLOSED\x10\x01\x12\x13\n" +
	"\x0fERROR_NOT_FOUND\x10\x022\xa2\x06\n" +
	"\bDatabase\x12,\n" +
	"\x03Has\x12\x11.rpcdb.HasRequest\x1a\x12.rpcdb.HasResponse\x12,\n" +
	"\x03Get\x12\x11.rpcdb.GetRequest\x1a\x12.rpcdb.GetResponse\x12,\n" +
	"\x03Put\x12\x11.rpcdb.PutRequest\x1a\x12.rpcdb.PutResponse\x125\n" +
	"\x06Delete\x12\x14.rpcdb.DeleteRequest\x1a\x15.rpcdb.DeleteResponse\x128\n" +
	"\aCompact\x12\x15.rpcdb.CompactRequest\x1a\x16.rpcdb.CompactResponse\x122\n" +
	"\x05Close\x12\x13.rpcdb.CloseRequest\x1a\x14.rpcdb.CloseResponse\x12A\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x1a.rpcdb.HealthCheckResponse\x12A\n" +
	"\n" +
	"WriteBatch\x12\x18.rpcdb.WriteBatchRequest\x1a\x19.rpcdb.WriteBatchResponse\x12z\n" +
	"\x1dNewIteratorWithStartAndPrefix\x12+.rpcdb.NewIteratorWithStartAndPrefixRequest\x1a,.rpcdb.NewIteratorWithStartAndPrefixResponse\x12G\n" +
	"\fIteratorNext\x12\x1a.rpcdb.IteratorNextRequest\x1a\x1b.rpcdb.IteratorNextResponse\x12J\n" +
	"\rIteratorError\x12\x1b.rpcdb.IteratorErrorRequest\x1a\x1c.rpcdb.IteratorErrorResponse\x12P\n" +
	"\x0fIteratorRelease\x12\x1d.rpcdb.IteratorReleaseRequest\x1a\x1e.rpcdb.IteratorReleaseResponseB0Z.github.com/ava-labs/avalanchego/proto/pb/rpcdbb\x06proto3"

var (
	file_rpcdb_rpcdb_proto_rawDescOnce sync.Once
	file_rpcdb_rpcdb_proto_rawDescData []byte
)

func file_rpcdb_rpcdb_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_rpcdb_rpcdb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpcdb_rpcdb_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_rpcdb_rpcdb_proto_goTypes = []any{
	(Error)(0),                                    // 0: rpcdb.Error
	(*HasRequest)(nil),                            // 1: rpcdb.HasRequest
	(*HasResponse)(nil),                           // 2: rpcdb.HasResponse
	(*GetRequest)(nil),                            // 3: rpcdb.GetRequest
	(*GetResponse)(nil),                           // 4: rpcdb.GetResponse
	(*PutRequest)(nil),                            // 5: rpcdb.PutRequest
	(*PutResponse)(nil),                           // 6: rpcdb.PutResponse
	(*DeleteRequest)(nil),                         // 7: rpcdb.DeleteRequest
	(*DeleteResponse)(nil),                        // 8: rpcdb.DeleteResponse
	(*CompactRequest)(nil),                        // 9: rpcdb.CompactRequest
	(*CompactResponse)(nil),                       // 10: rpcdb.CompactResponse
	(*CloseRequest)(nil),                          // 11: rpcdb.CloseRequest
	(*CloseResponse)(nil),                         // 12: rpcdb.CloseResponse
	(*WriteBatchRequest)(nil),                     // 13: rpcdb.WriteBatchRequest
	(*WriteBatchResponse)(nil),                    // 14: rpcdb.WriteBatchResponse
	(*NewIteratorRequest)(nil),                    // 15: rpcdb.NewIteratorRequest
	(*NewIteratorWithStartAndPrefixRequest)(nil),  // 16: rpcdb.NewIteratorWithStartAndPrefixRequest
	(*NewIteratorWithStartAndPrefixResponse)(nil), // 17: rpcdb.NewIteratorWithStartAndPrefixResponse
	(*IteratorNextRequest)(nil),                   // 18: rpcdb.IteratorNextRequest
	(*IteratorNextResponse)(nil),                  // 19: rpcdb.IteratorNextResponse
	(*IteratorErrorRequest)(nil),                  // 20: rpcdb.IteratorErrorRequest
	(*IteratorErrorResponse)(nil),                 // 21: rpcdb.IteratorErrorResponse
	(*IteratorReleaseRequest)(nil),                // 22: rpcdb.IteratorReleaseRequest
	(*IteratorReleaseResponse)(nil),               // 23: rpcdb.IteratorReleaseResponse
	(*HealthCheckResponse)(nil),                   // 24: rpcdb.HealthCheckResponse
	(*emptypb.Empty)(nil),                         // 25: google.protobuf.Empty
}
var file_rpcdb_rpcdb_proto_depIdxs = []int32{
	0,  // 0: rpcdb.HasResponse.err:type_name -> rpcdb.Error
	0,  // 1: rpcdb.GetResponse.err:type_name -> rpcdb.Error
	0,  // 2: rpcdb.PutResponse.err:type_name -> rpcdb.Error
	0,  // 3: rpcdb.DeleteResponse.err:type_name -> rpcdb.Error
	0,  // 4: rpcdb.CompactResponse.err:type_name -> rpcdb.Error
	0,  // 5: rpcdb.CloseResponse.err:type_name -> rpcdb.Error
	5,  // 6: rpcdb.WriteBatchRequest.puts:type_name -> rpcdb.PutRequest
	7,  // 7: rpcdb.WriteBatchRequest.deletes:type_name -> rpcdb.DeleteRequest
	0,  // 8: rpcdb.WriteBatchResponse.err:type_name -> rpcdb.Error
	5,  // 9: rpcdb.IteratorNextResponse.data:type_name -> rpcdb.PutRequest
	0,  // 10: rpcdb.IteratorErrorResponse.err:type_name -> rpcdb.Error
	0,  // 11: rpcdb.IteratorReleaseResponse.err:type_name -> rpcdb.Error
	1,  // 12: rpcdb.Database.Has:input_type -> rpcdb.HasRequest
	3,  // 13: rpcdb.Database.Get:input_type -> rpcdb.GetRequest
	5,  // 14: rpcdb.Database.Put:input_type -> rpcdb.PutRequest
	7,  // 15: rpcdb.Database.Delete:input_type -> rpcdb.DeleteRequest
	9,  // 16: rpcdb.Database.Compact:input_type -> rpcdb.CompactRequest
	11, // 17: rpcdb.Database.Close:input_type -> rpcdb.CloseRequest
	25, // 18: rpcdb.Database.HealthCheck:input_type -> google.protobuf.Empty
	13, // 19: rpcdb.Database.WriteBatch:input_type -> rpcdb.WriteBatchRequest
	16, // 20: rpcdb.Database.NewIteratorWithStartAndPrefix:input_type -> rpcdb.NewIteratorWithStartAndPrefixRequest
	18, // 21: rpcdb.Database.IteratorNext:input_type -> rpcdb.IteratorNextRequest
	20, // 22: rpcdb.Database.IteratorError:input_type -> rpcdb.IteratorErrorRequest
	22, // 23: rpcdb.Database.IteratorRelease:input_type -> rpcdb.IteratorReleaseRequest
	2,  // 24: rpcdb.Database.Has:output_type -> rpcdb.HasResponse
	4,  // 25: rpcdb.Database.Get:output_type -> rpcdb.GetResponse
	6,  // 26: rpcdb.Database.Put:output_type -> rpcdb.PutResponse
	8,  // 27: rpcdb.Database.Delete:output_type -> rpcdb.DeleteResponse
	10, // 28: rpcdb.Database.Compact:output_type -> rpcdb.CompactResponse
	12, // 29: rpcdb.Database.Close:output_type -> rpcdb.CloseResponse
	24, // 30: rpcdb.Database.HealthCheck:output_type -> rpcdb.HealthCheckResponse
	14, // 31: rpcdb.Database.WriteBatch:output_type -> rpcdb.WriteBatchResponse
	17, // 32: rpcdb.Database.NewIteratorWithStartAndPrefix:output_type -> rpcdb.NewIteratorWithStartAndPrefixResponse
	19, // 33: rpcdb.Database.IteratorNext:output_type -> rpcdb.IteratorNextResponse
	21, // 34: rpcdb.Database.IteratorError:output_type -> rpcdb.IteratorErrorResponse
	23, // 35: rpcdb.Database.IteratorRelease:output_type -> rpcdb.IteratorReleaseResponse
	24, // [24:36] is the sub-list for method output_type
	12, // [12:24] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init()                        { file_rpcdb_rpcdb_proto_init() }
func file_rpcdb_rpcdb_proto_init() { _ = "STUB: not implemented"; return }
