// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/chains/atomic (interfaces: SharedMemory)
//
// Generated by this command:
//
//	mockgen -package=atomicmock -destination=atomicmock/shared_memory.go -mock_names=SharedMemory=SharedMemory . SharedMemory
//

// Package atomicmock is a generated GoMock package.
package atomicmock

import (
	atomic "github.com/ava-labs/avalanchego/chains/atomic"
	database "github.com/ava-labs/avalanchego/database"
	ids "github.com/ava-labs/avalanchego/ids"
	gomock "go.uber.org/mock/gomock"
)

// SharedMemory is a mock of SharedMemory interface.
type SharedMemory struct {
	ctrl     *gomock.Controller
	recorder *SharedMemoryMockRecorder
	isgomock struct{}
}

// SharedMemoryMockRecorder is the mock recorder for SharedMemory.
type SharedMemoryMockRecorder struct {
	mock *SharedMemory
}

// NewSharedMemory creates a new mock instance.
func NewSharedMemory(ctrl *gomock.Controller) *SharedMemory { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *SharedMemory) EXPECT() *SharedMemoryMockRecorder {
	_ = "STUB: not implemented"

	// Apply mocks base method.
	return nil
}

func (m *SharedMemory) Apply(requests map[ids.ID]*atomic.Requests, batches ...database.Batch) error {
	_ = "STUB: not implemented"
	return nil
}

// Apply indicates an expected call of Apply.
func (mr *SharedMemoryMockRecorder) Apply(requests any, batches ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Get mocks base method.
func (m *SharedMemory) Get(peerChainID ids.ID, keys [][]byte) ([][]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Get indicates an expected call of Get.
func (mr *SharedMemoryMockRecorder) Get(peerChainID, keys any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Indexed mocks base method.
func (m *SharedMemory) Indexed(peerChainID ids.ID, traits [][]byte, startTrait, startKey []byte, limit int) ([][]byte, []byte, []byte, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil, nil
}

// Indexed indicates an expected call of Indexed.
func (mr *SharedMemoryMockRecorder) Indexed(peerChainID, traits, startTrait, startKey, limit any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
