// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: vm/runtime/runtime.proto

package manager

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Runtime_Initialize_FullMethodName = "/vm.runtime.Runtime/Initialize"
)

// RuntimeClient is the client API for Runtime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Manages the lifecycle of a subnet VM process.
type RuntimeClient interface {
	// Initialize a VM Runtime.
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type runtimeClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeClient(cc grpc.ClientConnInterface) RuntimeClient {
	_ = "STUB: not implemented"
	return *new(RuntimeClient)
}

func (c *runtimeClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RuntimeServer is the server API for Runtime service.
// All implementations must embed UnimplementedRuntimeServer
// for forward compatibility.
//
// Manages the lifecycle of a subnet VM process.
type RuntimeServer interface {
	// Initialize a VM Runtime.
	Initialize(context.Context, *InitializeRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedRuntimeServer()
}

// UnimplementedRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServer struct{}

func (UnimplementedRuntimeServer) Initialize(context.Context, *InitializeRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedRuntimeServer) mustEmbedUnimplementedRuntimeServer() {
	_ = "STUB: not implemented"
	return
}
func (UnimplementedRuntimeServer) testEmbeddedByValue() {
	_ = "STUB: not implemented"

	// UnsafeRuntimeServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to RuntimeServer will
	// result in compilation errors.
	return
}

type UnsafeRuntimeServer interface {
	mustEmbedUnimplementedRuntimeServer()
}

func RegisterRuntimeServer(s grpc.ServiceRegistrar, srv RuntimeServer) {
	_ = "STUB: not implemented"
	// If the following call pancis, it indicates UnimplementedRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _Runtime_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Runtime_ServiceDesc is the grpc.ServiceDesc for Runtime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runtime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vm.runtime.Runtime",
	HandlerType: (*RuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Initialize",
			Handler:    _Runtime_Initialize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vm/runtime/runtime.proto",
}
