// Code generated by MockGen and manually edited.
// Source: github.com/ava-labs/avalanchego/vms/components/avax (interfaces: TransferableOut)
//
// Generated by this command:
//
//	mockgen -package=avaxmock -destination=vms/components/avax/avaxmock/transferable_out.go -mock_names=TransferableOut=TransferableOut github.com/ava-labs/avalanchego/vms/components/avax TransferableOut
//

// Package avaxmock is a generated GoMock package.
package avaxmock

import (
	snow "github.com/ava-labs/avalanchego/snow"
	verify "github.com/ava-labs/avalanchego/vms/components/verify"
	gomock "go.uber.org/mock/gomock"
)

// TransferableOut is a mock of TransferableOut interface.
type TransferableOut struct {
	verify.IsState

	ctrl     *gomock.Controller
	recorder *TransferableOutMockRecorder
}

// TransferableOutMockRecorder is the mock recorder for TransferableOut.
type TransferableOutMockRecorder struct {
	mock *TransferableOut
}

// NewTransferableOut creates a new mock instance.
func NewTransferableOut(ctrl *gomock.Controller) *TransferableOut {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *TransferableOut) EXPECT() *TransferableOutMockRecorder {
	_ = "STUB: not implemented"

	// Amount mocks base method.
	return nil
}

func (m *TransferableOut) Amount() uint64 { _ = "STUB: not implemented"; return 0 }

// Amount indicates an expected call of Amount.
func (mr *TransferableOutMockRecorder) Amount() *gomock.Call { _ = "STUB: not implemented"; return nil }

// InitCtx mocks base method.
func (m *TransferableOut) InitCtx(arg0 *snow.Context) { _ = "STUB: not implemented"; return }

// InitCtx indicates an expected call of InitCtx.
func (mr *TransferableOutMockRecorder) InitCtx(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Verify mocks base method.
func (m *TransferableOut) Verify() error { _ = "STUB: not implemented"; return nil }

// Verify indicates an expected call of Verify.
func (mr *TransferableOutMockRecorder) Verify() *gomock.Call { _ = "STUB: not implemented"; return nil }

// isState mocks base method.
func (m *TransferableOut) isState() { _ = "STUB: not implemented"; return }

// isState indicates an expected call of isState.
func (mr *TransferableOutMockRecorder) isState() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
