// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/vms/components/avax (interfaces: TransferableIn)
//
// Generated by this command:
//
//	mockgen -package=avaxmock -destination=avaxmock/transferable_in.go -mock_names=TransferableIn=TransferableIn . TransferableIn
//

// Package avaxmock is a generated GoMock package.
package avaxmock

import (
	snow "github.com/ava-labs/avalanchego/snow"
	gomock "go.uber.org/mock/gomock"
)

// TransferableIn is a mock of TransferableIn interface.
type TransferableIn struct {
	ctrl     *gomock.Controller
	recorder *TransferableInMockRecorder
	isgomock struct{}
}

// TransferableInMockRecorder is the mock recorder for TransferableIn.
type TransferableInMockRecorder struct {
	mock *TransferableIn
}

// NewTransferableIn creates a new mock instance.
func NewTransferableIn(ctrl *gomock.Controller) *TransferableIn {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *TransferableIn) EXPECT() *TransferableInMockRecorder {
	_ = "STUB: not implemented"

	// Amount mocks base method.
	return nil
}

func (m *TransferableIn) Amount() uint64 { _ = "STUB: not implemented"; return 0 }

// Amount indicates an expected call of Amount.
func (mr *TransferableInMockRecorder) Amount() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Cost mocks base method.
func (m *TransferableIn) Cost() (uint64, error) { _ = "STUB: not implemented"; return 0, nil }

// Cost indicates an expected call of Cost.
func (mr *TransferableInMockRecorder) Cost() *gomock.Call { _ = "STUB: not implemented"; return nil }

// InitCtx mocks base method.
func (m *TransferableIn) InitCtx(ctx *snow.Context) { _ = "STUB: not implemented"; return }

// InitCtx indicates an expected call of InitCtx.
func (mr *TransferableInMockRecorder) InitCtx(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Verify mocks base method.
func (m *TransferableIn) Verify() error { _ = "STUB: not implemented"; return nil }

// Verify indicates an expected call of Verify.
func (mr *TransferableInMockRecorder) Verify() *gomock.Call { _ = "STUB: not implemented"; return nil }
