// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.18.0
// source: proxytime.go

package proxytime

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = canoto.VersionCompatibility - 1
	_ uint = 1 - canoto.VersionCompatibility
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__Time__seconds  = 1
	canoto__Time__fraction = 2
	canoto__Time__hertz    = 3

	canoto__Time__seconds__tag  = "\x08" // canoto.Tag(canoto__Time__seconds, canoto.Varint)
	canoto__Time__fraction__tag = "\x10" // canoto.Tag(canoto__Time__fraction, canoto.Varint)
	canoto__Time__hertz__tag    = "\x18" // canoto.Tag(canoto__Time__hertz, canoto.Varint)
)

type canotoData_Time struct {
	size atomic.Uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*Time[T1]) CanotoSpec(...reflect.Type) *canoto.Spec { _ = "STUB: not implemented"; return nil }

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *Time[T1]) UnmarshalCanoto(bytes []byte) error { _ = "STUB: not implemented"; return nil }

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *Time[T1]) UnmarshalCanotoFrom(r canoto.Reader) error {
	_ = "STUB: not implemented"
	// Zero the struct before unmarshaling.
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *Time[T1]) ValidCanoto() bool {
	_ = "STUB: not implemented"

	// CalculateCanotoCache populates size and OneOf caches based on the current
	// values in the struct.
	return false
}

func (c *Time[T1]) CalculateCanotoCache() { _ = "STUB: not implemented"; return }

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *Time[T1]) CachedCanotoSize() uint64 { _ = "STUB: not implemented"; return 0 }

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *Time[T1]) MarshalCanoto() []byte { _ = "STUB: not implemented"; return nil }

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *Time[T1]) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	_ = "STUB: not implemented"
	return *new(canoto.Writer)
}
