// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: io/reader/reader.proto

package reader

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode provides information for special sentinel error types
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	ErrorCode_ERROR_CODE_EOF         ErrorCode = 1
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_EOF",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED": 0,
		"ERROR_CODE_EOF":         1,
	}
)

func (x ErrorCode) Enum() *ErrorCode { _ = "STUB: not implemented"; return nil }

func (x ErrorCode) String() string { _ = "STUB: not implemented"; return "" }

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumDescriptor)
}

func (ErrorCode) Type() protoreflect.EnumType {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumType)
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	_ = "STUB: not implemented"
	return *new(protoreflect.EnumNumber)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type ReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// length is the request in bytes
	Length        int32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *ReadRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*ReadRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *ReadRequest) GetLength() int32 { _ = "STUB: not implemented"; return 0 }

type ReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// read is the payload in bytes
	Read []byte `protobuf:"bytes,1,opt,name=read,proto3" json:"read,omitempty"`
	// error is an error message
	Error         *Error `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *ReadResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*ReadResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *ReadResponse) GetRead() []byte { _ = "STUB: not implemented"; return nil }

func (x *ReadResponse) GetError() *Error { _ = "STUB: not implemented"; return nil }

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     ErrorCode              `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=io.reader.ErrorCode" json:"error_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() { _ = "STUB: not implemented"; return }

func (x *Error) String() string { _ = "STUB: not implemented"; return "" }

func (*Error) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Error) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Error) GetErrorCode() ErrorCode { _ = "STUB: not implemented"; return *new(ErrorCode) }

func (x *Error) GetMessage() string { _ = "STUB: not implemented"; return "" }

var File_io_reader_reader_proto protoreflect.FileDescriptor

const file_io_reader_reader_proto_rawDesc = "" +
	"\n" +
	"\x16io/reader/reader.proto\x12\tio.reader\"%\n" +
	"\vReadRequest\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x05R\x06length\"J\n" +
	"\fReadResponse\x12\x12\n" +
	"\x04read\x18\x01 \x01(\fR\x04read\x12&\n" +
	"\x05error\x18\x02 \x01(\v2\x10.io.reader.ErrorR\x05error\"V\n" +
	"\x05Error\x123\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x0e2\x14.io.reader.ErrorCodeR\terrorCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*;\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eERROR_CODE_EOF\x10\x012A\n" +
	"\x06Reader\x127\n" +
	"\x04Read\x12\x16.io.reader.ReadRequest\x1a\x17.io.reader.ReadResponseB4Z2github.com/ava-labs/avalanchego/proto/pb/io/readerb\x06proto3"

var (
	file_io_reader_reader_proto_rawDescOnce sync.Once
	file_io_reader_reader_proto_rawDescData []byte
)

func file_io_reader_reader_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_io_reader_reader_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_io_reader_reader_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_io_reader_reader_proto_goTypes = []any{
	(ErrorCode)(0),       // 0: io.reader.ErrorCode
	(*ReadRequest)(nil),  // 1: io.reader.ReadRequest
	(*ReadResponse)(nil), // 2: io.reader.ReadResponse
	(*Error)(nil),        // 3: io.reader.Error
}
var file_io_reader_reader_proto_depIdxs = []int32{
	3, // 0: io.reader.ReadResponse.error:type_name -> io.reader.Error
	0, // 1: io.reader.Error.error_code:type_name -> io.reader.ErrorCode
	1, // 2: io.reader.Reader.Read:input_type -> io.reader.ReadRequest
	2, // 3: io.reader.Reader.Read:output_type -> io.reader.ReadResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init()                             { file_io_reader_reader_proto_init() }
func file_io_reader_reader_proto_init() { _ = "STUB: not implemented"; return }
