// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: io/reader/reader.proto

package reader

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Reader_Read_FullMethodName = "/io.reader.Reader/Read"
)

// ReaderClient is the client API for Reader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Reader is an io.Reader see: https://pkg.go.dev/io#Reader
type ReaderClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
}

type readerClient struct {
	cc grpc.ClientConnInterface
}

func NewReaderClient(cc grpc.ClientConnInterface) ReaderClient {
	_ = "STUB: not implemented"
	return *new(ReaderClient)
}

func (c *readerClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReaderServer is the server API for Reader service.
// All implementations must embed UnimplementedReaderServer
// for forward compatibility.
//
// Reader is an io.Reader see: https://pkg.go.dev/io#Reader
type ReaderServer interface {
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	mustEmbedUnimplementedReaderServer()
}

// UnimplementedReaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReaderServer struct{}

func (UnimplementedReaderServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedReaderServer) mustEmbedUnimplementedReaderServer() {
	_ = "STUB: not implemented"
	return
}
func (UnimplementedReaderServer) testEmbeddedByValue() {
	_ = "STUB: not implemented"

	// UnsafeReaderServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to ReaderServer will
	// result in compilation errors.
	return
}

type UnsafeReaderServer interface {
	mustEmbedUnimplementedReaderServer()
}

func RegisterReaderServer(s grpc.ServiceRegistrar, srv ReaderServer) {
	_ = "STUB: not implemented"
	// If the following call pancis, it indicates UnimplementedReaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _Reader_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Reader_ServiceDesc is the grpc.ServiceDesc for Reader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.reader.Reader",
	HandlerType: (*ReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _Reader_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "io/reader/reader.proto",
}
