// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/utils/filesystem (interfaces: Reader)
//
// Generated by this command:
//
//	mockgen -package=filesystemmock -destination=filesystemmock/reader.go -mock_names=Reader=Reader . Reader
//

// Package filesystemmock is a generated GoMock package.
package filesystemmock

import (
	fs "io/fs"

	gomock "go.uber.org/mock/gomock"
)

// Reader is a mock of Reader interface.
type Reader struct {
	ctrl     *gomock.Controller
	recorder *ReaderMockRecorder
	isgomock struct{}
}

// ReaderMockRecorder is the mock recorder for Reader.
type ReaderMockRecorder struct {
	mock *Reader
}

// NewReader creates a new mock instance.
func NewReader(ctrl *gomock.Controller) *Reader { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Reader) EXPECT() *ReaderMockRecorder {
	_ = "STUB: not implemented"

	// ReadDir mocks base method.
	return nil
}

func (m *Reader) ReadDir(arg0 string) ([]fs.DirEntry, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadDir indicates an expected call of ReadDir.
func (mr *ReaderMockRecorder) ReadDir(arg0 any) *gomock.Call { _ = "STUB: not implemented"; return nil }
