// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: proposervm/service.proto

package proposervm

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to get the current proposed block height.
type GetProposedHeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProposedHeightRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *GetProposedHeightRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*GetProposedHeightRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *GetProposedHeightRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use GetProposedHeightRequest.ProtoReflect.Descriptor instead.
func (*GetProposedHeightRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Response containing the current proposed P-chain block height.
type GetProposedHeightReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The P-chain height that would be included in a block if it were proposed
	// right now.
	Height        uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProposedHeightReply) Reset() { _ = "STUB: not implemented"; return }

func (x *GetProposedHeightReply) String() string { _ = "STUB: not implemented"; return "" }

func (*GetProposedHeightReply) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *GetProposedHeightReply) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use GetProposedHeightReply.ProtoReflect.Descriptor instead.
func (*GetProposedHeightReply) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *GetProposedHeightReply) GetHeight() uint64 { _ = "STUB: not implemented"; return 0 }

// Request to get the current epoch.
type GetCurrentEpochRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentEpochRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *GetCurrentEpochRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*GetCurrentEpochRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *GetCurrentEpochRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use GetCurrentEpochRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentEpochRequest) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Response containing the current epoch.
type GetCurrentEpochReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of the current epoch.
	Number uint64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	// P-chain height which used to verify ICM messages for this epoch.
	PChainHeight uint64 `protobuf:"varint,2,opt,name=p_chain_height,json=pChainHeight,proto3" json:"p_chain_height,omitempty"`
	// Start time of this epoch in Unix time (seconds).
	StartTime     int64 `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentEpochReply) Reset() { _ = "STUB: not implemented"; return }

func (x *GetCurrentEpochReply) String() string { _ = "STUB: not implemented"; return "" }

func (*GetCurrentEpochReply) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *GetCurrentEpochReply) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use GetCurrentEpochReply.ProtoReflect.Descriptor instead.
func (*GetCurrentEpochReply) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *GetCurrentEpochReply) GetNumber() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *GetCurrentEpochReply) GetPChainHeight() uint64 { _ = "STUB: not implemented"; return 0 }

func (x *GetCurrentEpochReply) GetStartTime() int64 { _ = "STUB: not implemented"; return 0 }

var File_proposervm_service_proto protoreflect.FileDescriptor

const file_proposervm_service_proto_rawDesc = "" +
	"\n" +
	"\x18proposervm/service.proto\x12\n" +
	"proposervm\"\x1a\n" +
	"\x18GetProposedHeightRequest\"0\n" +
	"\x16GetProposedHeightReply\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\"\x18\n" +
	"\x16GetCurrentEpochRequest\"s\n" +
	"\x14GetCurrentEpochReply\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12$\n" +
	"\x0ep_chain_height\x18\x02 \x01(\x04R\fpChainHeight\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime2\xc4\x01\n" +
	"\n" +
	"ProposerVM\x12]\n" +
	"\x11GetProposedHeight\x12$.proposervm.GetProposedHeightRequest\x1a\".proposervm.GetProposedHeightReply\x12W\n" +
	"\x0fGetCurrentEpoch\x12\".proposervm.GetCurrentEpochRequest\x1a .proposervm.GetCurrentEpochReplyB<Z:github.com/ava-labs/avalanchego/connectproto/pb/proposervmb\x06proto3"

var (
	file_proposervm_service_proto_rawDescOnce sync.Once
	file_proposervm_service_proto_rawDescData []byte
)

func file_proposervm_service_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_proposervm_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proposervm_service_proto_goTypes = []any{
	(*GetProposedHeightRequest)(nil), // 0: proposervm.GetProposedHeightRequest
	(*GetProposedHeightReply)(nil),   // 1: proposervm.GetProposedHeightReply
	(*GetCurrentEpochRequest)(nil),   // 2: proposervm.GetCurrentEpochRequest
	(*GetCurrentEpochReply)(nil),     // 3: proposervm.GetCurrentEpochReply
}
var file_proposervm_service_proto_depIdxs = []int32{
	0, // 0: proposervm.ProposerVM.GetProposedHeight:input_type -> proposervm.GetProposedHeightRequest
	2, // 1: proposervm.ProposerVM.GetCurrentEpoch:input_type -> proposervm.GetCurrentEpochRequest
	1, // 2: proposervm.ProposerVM.GetProposedHeight:output_type -> proposervm.GetProposedHeightReply
	3, // 3: proposervm.ProposerVM.GetCurrentEpoch:output_type -> proposervm.GetCurrentEpochReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                               { file_proposervm_service_proto_init() }
func file_proposervm_service_proto_init() { _ = "STUB: not implemented"; return }
