// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/vms/registry (interfaces: VMGetter)
//
// Generated by this command:
//
//	mockgen -package=registrymock -destination=registrymock/vm_getter.go -mock_names=VMGetter=VMGetter . VMGetter
//

// Package registrymock is a generated GoMock package.
package registrymock

import (
	ids "github.com/ava-labs/avalanchego/ids"
	vms "github.com/ava-labs/avalanchego/vms"
	gomock "go.uber.org/mock/gomock"
)

// VMGetter is a mock of VMGetter interface.
type VMGetter struct {
	ctrl     *gomock.Controller
	recorder *VMGetterMockRecorder
	isgomock struct{}
}

// VMGetterMockRecorder is the mock recorder for VMGetter.
type VMGetterMockRecorder struct {
	mock *VMGetter
}

// NewVMGetter creates a new mock instance.
func NewVMGetter(ctrl *gomock.Controller) *VMGetter { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *VMGetter) EXPECT() *VMGetterMockRecorder {
	_ = "STUB: not implemented"

	// Get mocks base method.
	return nil
}

func (m *VMGetter) Get() (map[ids.ID]vms.Factory, map[ids.ID]vms.Factory, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// Get indicates an expected call of Get.
func (mr *VMGetterMockRecorder) Get() *gomock.Call { _ = "STUB: not implemented"; return nil }
