// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/vms/registry (interfaces: VMRegistry)
//
// Generated by this command:
//
//	mockgen -package=registrymock -destination=registrymock/vm_registry.go -mock_names=VMRegistry=VMRegistry . VMRegistry
//

// Package registrymock is a generated GoMock package.
package registrymock

import (
	context "context"

	ids "github.com/ava-labs/avalanchego/ids"
	gomock "go.uber.org/mock/gomock"
)

// VMRegistry is a mock of VMRegistry interface.
type VMRegistry struct {
	ctrl     *gomock.Controller
	recorder *VMRegistryMockRecorder
	isgomock struct{}
}

// VMRegistryMockRecorder is the mock recorder for VMRegistry.
type VMRegistryMockRecorder struct {
	mock *VMRegistry
}

// NewVMRegistry creates a new mock instance.
func NewVMRegistry(ctrl *gomock.Controller) *VMRegistry { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *VMRegistry) EXPECT() *VMRegistryMockRecorder {
	_ = "STUB: not implemented"

	// Reload mocks base method.
	return nil
}

func (m *VMRegistry) Reload(ctx context.Context) ([]ids.ID, map[ids.ID]error, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// Reload indicates an expected call of Reload.
func (mr *VMRegistryMockRecorder) Reload(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
