// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/vms/avm/block/executor (interfaces: Manager)
//
// Generated by this command:
//
//	mockgen -package=executormock -destination=executormock/manager.go -mock_names=Manager=Manager . Manager
//

// Package executormock is a generated GoMock package.
package executormock

import (
	ids "github.com/ava-labs/avalanchego/ids"
	snowman "github.com/ava-labs/avalanchego/snow/consensus/snowman"
	set "github.com/ava-labs/avalanchego/utils/set"
	block "github.com/ava-labs/avalanchego/vms/avm/block"
	state "github.com/ava-labs/avalanchego/vms/avm/state"
	txs "github.com/ava-labs/avalanchego/vms/avm/txs"
	gomock "go.uber.org/mock/gomock"
)

// Manager is a mock of Manager interface.
type Manager struct {
	ctrl     *gomock.Controller
	recorder *ManagerMockRecorder
	isgomock struct{}
}

// ManagerMockRecorder is the mock recorder for Manager.
type ManagerMockRecorder struct {
	mock *Manager
}

// NewManager creates a new mock instance.
func NewManager(ctrl *gomock.Controller) *Manager { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Manager) EXPECT() *ManagerMockRecorder {
	_ = "STUB: not implemented"

	// GetBlock mocks base method.
	return nil
}

func (m *Manager) GetBlock(blkID ids.ID) (snowman.Block, error) {
	_ = "STUB: not implemented"
	return *new(snowman.Block), nil
}

// GetBlock indicates an expected call of GetBlock.
func (mr *ManagerMockRecorder) GetBlock(blkID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetState mocks base method.
func (m *Manager) GetState(blkID ids.ID) (state.Chain, bool) {
	_ = "STUB: not implemented"
	return *new(state.Chain), false
}

// GetState indicates an expected call of GetState.
func (mr *ManagerMockRecorder) GetState(blkID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetStatelessBlock mocks base method.
func (m *Manager) GetStatelessBlock(blkID ids.ID) (block.Block, error) {
	_ = "STUB: not implemented"
	return *new(block.Block), nil
}

// GetStatelessBlock indicates an expected call of GetStatelessBlock.
func (mr *ManagerMockRecorder) GetStatelessBlock(blkID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LastAccepted mocks base method.
func (m *Manager) LastAccepted() ids.ID { _ = "STUB: not implemented"; return *new(ids.ID) }

// LastAccepted indicates an expected call of LastAccepted.
func (mr *ManagerMockRecorder) LastAccepted() *gomock.Call { _ = "STUB: not implemented"; return nil }

// NewBlock mocks base method.
func (m *Manager) NewBlock(arg0 block.Block) snowman.Block {
	_ = "STUB: not implemented"
	return *new(snowman.Block)
}

// NewBlock indicates an expected call of NewBlock.
func (mr *ManagerMockRecorder) NewBlock(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Preferred mocks base method.
func (m *Manager) Preferred() ids.ID { _ = "STUB: not implemented"; return *new(ids.ID) }

// Preferred indicates an expected call of Preferred.
func (mr *ManagerMockRecorder) Preferred() *gomock.Call { _ = "STUB: not implemented"; return nil }

// SetPreference mocks base method.
func (m *Manager) SetPreference(blkID ids.ID) { _ = "STUB: not implemented"; return }

// SetPreference indicates an expected call of SetPreference.
func (mr *ManagerMockRecorder) SetPreference(blkID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// VerifyTx mocks base method.
func (m *Manager) VerifyTx(tx *txs.Tx) error { _ = "STUB: not implemented"; return nil }

// VerifyTx indicates an expected call of VerifyTx.
func (mr *ManagerMockRecorder) VerifyTx(tx any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// VerifyUniqueInputs mocks base method.
func (m *Manager) VerifyUniqueInputs(blkID ids.ID, inputs set.Set[ids.ID]) error {
	_ = "STUB: not implemented"
	return nil
}

// VerifyUniqueInputs indicates an expected call of VerifyUniqueInputs.
func (mr *ManagerMockRecorder) VerifyUniqueInputs(blkID, inputs any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
