// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: platformvm/platformvm.proto

package platformvm

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type L1ValidatorRegistrationJustification struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Preimage:
	//
	//	*L1ValidatorRegistrationJustification_ConvertSubnetToL1TxData
	//	*L1ValidatorRegistrationJustification_RegisterL1ValidatorMessage
	Preimage      isL1ValidatorRegistrationJustification_Preimage `protobuf_oneof:"preimage"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L1ValidatorRegistrationJustification) Reset() { _ = "STUB: not implemented"; return }

func (x *L1ValidatorRegistrationJustification) String() string {
	_ = "STUB: not implemented"
	return ""
}

func (*L1ValidatorRegistrationJustification) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *L1ValidatorRegistrationJustification) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use L1ValidatorRegistrationJustification.ProtoReflect.Descriptor instead.
func (*L1ValidatorRegistrationJustification) Descriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (x *L1ValidatorRegistrationJustification) GetPreimage() isL1ValidatorRegistrationJustification_Preimage {
	_ = "STUB: not implemented"
	return *new(isL1ValidatorRegistrationJustification_Preimage)
}

func (x *L1ValidatorRegistrationJustification) GetConvertSubnetToL1TxData() *SubnetIDIndex {
	_ = "STUB: not implemented"
	return nil
}

func (x *L1ValidatorRegistrationJustification) GetRegisterL1ValidatorMessage() []byte {
	_ = "STUB: not implemented"
	return nil
}

type isL1ValidatorRegistrationJustification_Preimage interface {
	isL1ValidatorRegistrationJustification_Preimage()
}

type L1ValidatorRegistrationJustification_ConvertSubnetToL1TxData struct {
	// This should be set to obtain an attestation that a validator specified in
	// a ConvertSubnetToL1Tx has been removed from the validator set.
	ConvertSubnetToL1TxData *SubnetIDIndex `protobuf:"bytes,1,opt,name=convert_subnet_to_l1_tx_data,json=convertSubnetToL1TxData,proto3,oneof"`
}

type L1ValidatorRegistrationJustification_RegisterL1ValidatorMessage struct {
	// This should be set to a RegisterL1ValidatorMessage to obtain an
	// attestation that a validator is not currently registered and can never be
	// registered. This can be because the validator was successfully added and
	// then later removed, or because the validator was never added and the
	// registration expired.
	RegisterL1ValidatorMessage []byte `protobuf:"bytes,2,opt,name=register_l1_validator_message,json=registerL1ValidatorMessage,proto3,oneof"`
}

func (*L1ValidatorRegistrationJustification_ConvertSubnetToL1TxData) isL1ValidatorRegistrationJustification_Preimage() {
	_ = "STUB: not implemented"
	return
}

func (*L1ValidatorRegistrationJustification_RegisterL1ValidatorMessage) isL1ValidatorRegistrationJustification_Preimage() {
	_ = "STUB: not implemented"
	return
}

type SubnetIDIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubnetId      []byte                 `protobuf:"bytes,1,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubnetIDIndex) Reset() { _ = "STUB: not implemented"; return }

func (x *SubnetIDIndex) String() string { _ = "STUB: not implemented"; return "" }

func (*SubnetIDIndex) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *SubnetIDIndex) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use SubnetIDIndex.ProtoReflect.Descriptor instead.
func (*SubnetIDIndex) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *SubnetIDIndex) GetSubnetId() []byte { _ = "STUB: not implemented"; return nil }

func (x *SubnetIDIndex) GetIndex() uint32 { _ = "STUB: not implemented"; return 0 }

var File_platformvm_platformvm_proto protoreflect.FileDescriptor

const file_platformvm_platformvm_proto_rawDesc = "" +
	"\n" +
	"\x1bplatformvm/platformvm.proto\x12\n" +
	"platformvm\"\xd3\x01\n" +
	"$L1ValidatorRegistrationJustification\x12Z\n" +
	"\x1cconvert_subnet_to_l1_tx_data\x18\x01 \x01(\v2\x19.platformvm.SubnetIDIndexH\x00R\x17convertSubnetToL1TxData\x12C\n" +
	"\x1dregister_l1_validator_message\x18\x02 \x01(\fH\x00R\x1aregisterL1ValidatorMessageB\n" +
	"\n" +
	"\bpreimage\"B\n" +
	"\rSubnetIDIndex\x12\x1b\n" +
	"\tsubnet_id\x18\x01 \x01(\fR\bsubnetId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05indexB5Z3github.com/ava-labs/avalanchego/proto/pb/platformvmb\x06proto3"

var (
	file_platformvm_platformvm_proto_rawDescOnce sync.Once
	file_platformvm_platformvm_proto_rawDescData []byte
)

func file_platformvm_platformvm_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_platformvm_platformvm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_platformvm_platformvm_proto_goTypes = []any{
	(*L1ValidatorRegistrationJustification)(nil), // 0: platformvm.L1ValidatorRegistrationJustification
	(*SubnetIDIndex)(nil),                        // 1: platformvm.SubnetIDIndex
}
var file_platformvm_platformvm_proto_depIdxs = []int32{
	1, // 0: platformvm.L1ValidatorRegistrationJustification.convert_subnet_to_l1_tx_data:type_name -> platformvm.SubnetIDIndex
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init()                                  { file_platformvm_platformvm_proto_init() }
func file_platformvm_platformvm_proto_init() { _ = "STUB: not implemented"; return }
