// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.18.0
// source: storage.go

package simplex

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = canoto.VersionCompatibility - 1
	_ uint = 1 - canoto.VersionCompatibility
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__canotoFinalization__Finalization = 1
	canoto__canotoFinalization__QC           = 2

	canoto__canotoFinalization__Finalization__tag = "\x0a" // canoto.Tag(canoto__canotoFinalization__Finalization, canoto.Len)
	canoto__canotoFinalization__QC__tag           = "\x12" // canoto.Tag(canoto__canotoFinalization__QC, canoto.Len)
)

type canotoData_canotoFinalization struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*canotoFinalization) CanotoSpec(...reflect.Type) *canoto.Spec {
	_ = "STUB: not implemented"
	return nil
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *canotoFinalization) UnmarshalCanoto(bytes []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *canotoFinalization) UnmarshalCanotoFrom(r canoto.Reader) error {
	_ = "STUB: not implemented"
	// Zero the struct before unmarshaling.
	return nil
}

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *canotoFinalization) ValidCanoto() bool {
	_ = "STUB: not implemented"

	// CalculateCanotoCache populates size and OneOf caches based on the current
	// values in the struct.
	//
	// It is not safe to copy this struct concurrently.
	return false
}

func (c *canotoFinalization) CalculateCanotoCache() { _ = "STUB: not implemented"; return }

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *canotoFinalization) CachedCanotoSize() uint64 { _ = "STUB: not implemented"; return 0 }

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *canotoFinalization) MarshalCanoto() []byte { _ = "STUB: not implemented"; return nil }

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *canotoFinalization) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	_ = "STUB: not implemented"
	return *new(canoto.Writer)
}
