// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: http/responsewriter/responsewriter.proto

package responsewriter

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is a element key in a key value pair
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// values are a list of strings coresponding to the key
	Values        []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() { _ = "STUB: not implemented"; return }

func (x *Header) String() string { _ = "STUB: not implemented"; return "" }

func (*Header) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Header) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Header) GetKey() string { _ = "STUB: not implemented"; return "" }

func (x *Header) GetValues() []string { _ = "STUB: not implemented"; return nil }

type WriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// headers represents the key-value pairs in an HTTP header
	Headers []*Header `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	// payload is the write request in bytes
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *WriteRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*WriteRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *WriteRequest) GetHeaders() []*Header { _ = "STUB: not implemented"; return nil }

func (x *WriteRequest) GetPayload() []byte { _ = "STUB: not implemented"; return nil }

type WriteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// written is the number of bytes written in body
	Written       int32 `protobuf:"varint,1,opt,name=written,proto3" json:"written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *WriteResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*WriteResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *WriteResponse) GetWritten() int32 { _ = "STUB: not implemented"; return 0 }

type WriteHeaderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// headers represents the key-value pairs in an HTTP header
	Headers []*Header `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	// status_code must be a valid HTTP 1xx-5xx status code
	StatusCode    int32 `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteHeaderRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *WriteHeaderRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*WriteHeaderRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *WriteHeaderRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use WriteHeaderRequest.ProtoReflect.Descriptor instead.
func (*WriteHeaderRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *WriteHeaderRequest) GetHeaders() []*Header { _ = "STUB: not implemented"; return nil }

func (x *WriteHeaderRequest) GetStatusCode() int32 { _ = "STUB: not implemented"; return 0 }

type HijackResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// local_network is the name of the network (for example, "tcp", "udp")
	LocalNetwork string `protobuf:"bytes,1,opt,name=local_network,json=localNetwork,proto3" json:"local_network,omitempty"`
	// local_string is string form of address
	LocalString string `protobuf:"bytes,2,opt,name=local_string,json=localString,proto3" json:"local_string,omitempty"`
	// remote_network is the name of the network (for example, "tcp", "udp")
	RemoteNetwork string `protobuf:"bytes,3,opt,name=remote_network,json=remoteNetwork,proto3" json:"remote_network,omitempty"`
	// remote_string is string form of address
	RemoteString string `protobuf:"bytes,4,opt,name=remote_string,json=remoteString,proto3" json:"remote_string,omitempty"`
	// server_addr is the address of the gRPC server serving the Conn, Reader
	// and Writer services which facilitate Hijacking
	ServerAddr    string `protobuf:"bytes,5,opt,name=server_addr,json=serverAddr,proto3" json:"server_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HijackResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *HijackResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*HijackResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *HijackResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use HijackResponse.ProtoReflect.Descriptor instead.
func (*HijackResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *HijackResponse) GetLocalNetwork() string { _ = "STUB: not implemented"; return "" }

func (x *HijackResponse) GetLocalString() string { _ = "STUB: not implemented"; return "" }

func (x *HijackResponse) GetRemoteNetwork() string { _ = "STUB: not implemented"; return "" }

func (x *HijackResponse) GetRemoteString() string { _ = "STUB: not implemented"; return "" }

func (x *HijackResponse) GetServerAddr() string { _ = "STUB: not implemented"; return "" }

var File_http_responsewriter_responsewriter_proto protoreflect.FileDescriptor

const file_http_responsewriter_responsewriter_proto_rawDesc = "" +
	"\n" +
	"(http/responsewriter/responsewriter.proto\x12\x13http.responsewriter\x1a\x1bgoogle/protobuf/empty.proto\"2\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"_\n" +
	"\fWriteRequest\x125\n" +
	"\aheaders\x18\x01 \x03(\v2\x1b.http.responsewriter.HeaderR\aheaders\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\")\n" +
	"\rWriteResponse\x12\x18\n" +
	"\awritten\x18\x01 \x01(\x05R\awritten\"l\n" +
	"\x12WriteHeaderRequest\x125\n" +
	"\aheaders\x18\x01 \x03(\v2\x1b.http.responsewriter.HeaderR\aheaders\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\"\xc5\x01\n" +
	"\x0eHijackResponse\x12#\n" +
	"\rlocal_network\x18\x01 \x01(\tR\flocalNetwork\x12!\n" +
	"\flocal_string\x18\x02 \x01(\tR\vlocalString\x12%\n" +
	"\x0eremote_network\x18\x03 \x01(\tR\rremoteNetwork\x12#\n" +
	"\rremote_string\x18\x04 \x01(\tR\fremoteString\x12\x1f\n" +
	"\vserver_addr\x18\x05 \x01(\tR\n" +
	"serverAddr2\xa8\x02\n" +
	"\x06Writer\x12N\n" +
	"\x05Write\x12!.http.responsewriter.WriteRequest\x1a\".http.responsewriter.WriteResponse\x12N\n" +
	"\vWriteHeader\x12'.http.responsewriter.WriteHeaderRequest\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x05Flush\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\x06Hijack\x12\x16.google.protobuf.Empty\x1a#.http.responsewriter.HijackResponseB>Z<github.com/ava-labs/avalanchego/proto/pb/http/responsewriterb\x06proto3"

var (
	file_http_responsewriter_responsewriter_proto_rawDescOnce sync.Once
	file_http_responsewriter_responsewriter_proto_rawDescData []byte
)

func file_http_responsewriter_responsewriter_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_http_responsewriter_responsewriter_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_http_responsewriter_responsewriter_proto_goTypes = []any{
	(*Header)(nil),             // 0: http.responsewriter.Header
	(*WriteRequest)(nil),       // 1: http.responsewriter.WriteRequest
	(*WriteResponse)(nil),      // 2: http.responsewriter.WriteResponse
	(*WriteHeaderRequest)(nil), // 3: http.responsewriter.WriteHeaderRequest
	(*HijackResponse)(nil),     // 4: http.responsewriter.HijackResponse
	(*emptypb.Empty)(nil),      // 5: google.protobuf.Empty
}
var file_http_responsewriter_responsewriter_proto_depIdxs = []int32{
	0, // 0: http.responsewriter.WriteRequest.headers:type_name -> http.responsewriter.Header
	0, // 1: http.responsewriter.WriteHeaderRequest.headers:type_name -> http.responsewriter.Header
	1, // 2: http.responsewriter.Writer.Write:input_type -> http.responsewriter.WriteRequest
	3, // 3: http.responsewriter.Writer.WriteHeader:input_type -> http.responsewriter.WriteHeaderRequest
	5, // 4: http.responsewriter.Writer.Flush:input_type -> google.protobuf.Empty
	5, // 5: http.responsewriter.Writer.Hijack:input_type -> google.protobuf.Empty
	2, // 6: http.responsewriter.Writer.Write:output_type -> http.responsewriter.WriteResponse
	5, // 7: http.responsewriter.Writer.WriteHeader:output_type -> google.protobuf.Empty
	5, // 8: http.responsewriter.Writer.Flush:output_type -> google.protobuf.Empty
	4, // 9: http.responsewriter.Writer.Hijack:output_type -> http.responsewriter.HijackResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init()                                               { file_http_responsewriter_responsewriter_proto_init() }
func file_http_responsewriter_responsewriter_proto_init() { _ = "STUB: not implemented"; return }
