// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: appsender/appsender.proto

package appsender

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppSender_SendAppRequest_FullMethodName  = "/appsender.AppSender/SendAppRequest"
	AppSender_SendAppResponse_FullMethodName = "/appsender.AppSender/SendAppResponse"
	AppSender_SendAppError_FullMethodName    = "/appsender.AppSender/SendAppError"
	AppSender_SendAppGossip_FullMethodName   = "/appsender.AppSender/SendAppGossip"
)

// AppSenderClient is the client API for AppSender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppSenderClient interface {
	SendAppRequest(ctx context.Context, in *SendAppRequestMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendAppResponse(ctx context.Context, in *SendAppResponseMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendAppError(ctx context.Context, in *SendAppErrorMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendAppGossip(ctx context.Context, in *SendAppGossipMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type appSenderClient struct {
	cc grpc.ClientConnInterface
}

func NewAppSenderClient(cc grpc.ClientConnInterface) AppSenderClient {
	_ = "STUB: not implemented"
	return *new(AppSenderClient)
}

func (c *appSenderClient) SendAppRequest(ctx context.Context, in *SendAppRequestMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *appSenderClient) SendAppResponse(ctx context.Context, in *SendAppResponseMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *appSenderClient) SendAppError(ctx context.Context, in *SendAppErrorMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *appSenderClient) SendAppGossip(ctx context.Context, in *SendAppGossipMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AppSenderServer is the server API for AppSender service.
// All implementations must embed UnimplementedAppSenderServer
// for forward compatibility.
type AppSenderServer interface {
	SendAppRequest(context.Context, *SendAppRequestMsg) (*emptypb.Empty, error)
	SendAppResponse(context.Context, *SendAppResponseMsg) (*emptypb.Empty, error)
	SendAppError(context.Context, *SendAppErrorMsg) (*emptypb.Empty, error)
	SendAppGossip(context.Context, *SendAppGossipMsg) (*emptypb.Empty, error)
	mustEmbedUnimplementedAppSenderServer()
}

// UnimplementedAppSenderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppSenderServer struct{}

func (UnimplementedAppSenderServer) SendAppRequest(context.Context, *SendAppRequestMsg) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAppSenderServer) SendAppResponse(context.Context, *SendAppResponseMsg) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAppSenderServer) SendAppError(context.Context, *SendAppErrorMsg) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAppSenderServer) SendAppGossip(context.Context, *SendAppGossipMsg) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAppSenderServer) mustEmbedUnimplementedAppSenderServer() {
	_ = "STUB: not implemented"
	return
}
func (UnimplementedAppSenderServer) testEmbeddedByValue() {
	_ = "STUB: not implemented"

	// UnsafeAppSenderServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to AppSenderServer will
	// result in compilation errors.
	return
}

type UnsafeAppSenderServer interface {
	mustEmbedUnimplementedAppSenderServer()
}

func RegisterAppSenderServer(s grpc.ServiceRegistrar, srv AppSenderServer) {
	_ = "STUB: not implemented"
	// If the following call pancis, it indicates UnimplementedAppSenderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _AppSender_SendAppRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AppSender_SendAppResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AppSender_SendAppError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AppSender_SendAppGossip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AppSender_ServiceDesc is the grpc.ServiceDesc for AppSender service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppSender_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "appsender.AppSender",
	HandlerType: (*AppSenderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAppRequest",
			Handler:    _AppSender_SendAppRequest_Handler,
		},
		{
			MethodName: "SendAppResponse",
			Handler:    _AppSender_SendAppResponse_Handler,
		},
		{
			MethodName: "SendAppError",
			Handler:    _AppSender_SendAppError_Handler,
		},
		{
			MethodName: "SendAppGossip",
			Handler:    _AppSender_SendAppGossip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "appsender/appsender.proto",
}
