// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: aliasreader/aliasreader.proto

package aliasreader

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ID) Reset() { _ = "STUB: not implemented"; return }

func (x *ID) String() string { _ = "STUB: not implemented"; return "" }

func (*ID) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ID) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *ID) GetId() []byte { _ = "STUB: not implemented"; return nil }

type Alias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alias         string                 `protobuf:"bytes,1,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alias) Reset() { _ = "STUB: not implemented"; return }

func (x *Alias) String() string { _ = "STUB: not implemented"; return "" }

func (*Alias) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Alias) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Alias.ProtoReflect.Descriptor instead.
func (*Alias) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Alias) GetAlias() string { _ = "STUB: not implemented"; return "" }

type AliasList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aliases       []string               `protobuf:"bytes,1,rep,name=aliases,proto3" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliasList) Reset() { _ = "STUB: not implemented"; return }

func (x *AliasList) String() string { _ = "STUB: not implemented"; return "" }

func (*AliasList) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *AliasList) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use AliasList.ProtoReflect.Descriptor instead.
func (*AliasList) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *AliasList) GetAliases() []string { _ = "STUB: not implemented"; return nil }

var File_aliasreader_aliasreader_proto protoreflect.FileDescriptor

const file_aliasreader_aliasreader_proto_rawDesc = "" +
	"\n" +
	"\x1daliasreader/aliasreader.proto\x12\valiasreader\"\x14\n" +
	"\x02ID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\x1d\n" +
	"\x05Alias\x12\x14\n" +
	"\x05alias\x18\x01 \x01(\tR\x05alias\"%\n" +
	"\tAliasList\x12\x18\n" +
	"\aaliases\x18\x01 \x03(\tR\aaliases2\xa5\x01\n" +
	"\vAliasReader\x12-\n" +
	"\x06Lookup\x12\x12.aliasreader.Alias\x1a\x0f.aliasreader.ID\x123\n" +
	"\fPrimaryAlias\x12\x0f.aliasreader.ID\x1a\x12.aliasreader.Alias\x122\n" +
	"\aAliases\x12\x0f.aliasreader.ID\x1a\x16.aliasreader.AliasListB6Z4github.com/ava-labs/avalanchego/proto/pb/aliasreaderb\x06proto3"

var (
	file_aliasreader_aliasreader_proto_rawDescOnce sync.Once
	file_aliasreader_aliasreader_proto_rawDescData []byte
)

func file_aliasreader_aliasreader_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_aliasreader_aliasreader_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_aliasreader_aliasreader_proto_goTypes = []any{
	(*ID)(nil),        // 0: aliasreader.ID
	(*Alias)(nil),     // 1: aliasreader.Alias
	(*AliasList)(nil), // 2: aliasreader.AliasList
}
var file_aliasreader_aliasreader_proto_depIdxs = []int32{
	1, // 0: aliasreader.AliasReader.Lookup:input_type -> aliasreader.Alias
	0, // 1: aliasreader.AliasReader.PrimaryAlias:input_type -> aliasreader.ID
	0, // 2: aliasreader.AliasReader.Aliases:input_type -> aliasreader.ID
	0, // 3: aliasreader.AliasReader.Lookup:output_type -> aliasreader.ID
	1, // 4: aliasreader.AliasReader.PrimaryAlias:output_type -> aliasreader.Alias
	2, // 5: aliasreader.AliasReader.Aliases:output_type -> aliasreader.AliasList
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                                    { file_aliasreader_aliasreader_proto_init() }
func file_aliasreader_aliasreader_proto_init() { _ = "STUB: not implemented"; return }
