// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.18.0
// source: stub.go

package hookstest

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = canoto.VersionCompatibility - 1
	_ uint = 1 - canoto.VersionCompatibility
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__extra__subSec        = 1
	canoto__extra__ops           = 2
	canoto__extra__settledHeight = 3

	canoto__extra__subSec__tag        = "\x08" // canoto.Tag(canoto__extra__subSec, canoto.Varint)
	canoto__extra__ops__tag           = "\x12" // canoto.Tag(canoto__extra__ops, canoto.Len)
	canoto__extra__settledHeight__tag = "\x18" // canoto.Tag(canoto__extra__settledHeight, canoto.Varint)
)

type canotoData_extra struct {
	size uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*extra) CanotoSpec(types ...reflect.Type) *canoto.Spec { _ = "STUB: not implemented"; return nil }

/*type inference:*/
/*FieldNumber:   */
/*Name:          */
/*FixedLength:   */
/*Repeated:      */
/*OneOf:         */
/*Pointer:       */
/*types:         */

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *extra) UnmarshalCanoto(bytes []byte) error { _ = "STUB: not implemented"; return nil }

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *extra) UnmarshalCanotoFrom(r canoto.Reader) error {
	_ = "STUB: not implemented"
	// Zero the struct before unmarshaling.
	return nil
}

// Read the first entry manually because the tag is already
// stripped.

// Count the number of additional entries after the first entry.

// Read the rest of the entries, stripping the tag each time.

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *extra) ValidCanoto() bool { _ = "STUB: not implemented"; return false }

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *extra) CalculateCanotoCache() { _ = "STUB: not implemented"; return }

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *extra) CachedCanotoSize() uint64 { _ = "STUB: not implemented"; return 0 }

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *extra) MarshalCanoto() []byte { _ = "STUB: not implemented"; return nil }

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *extra) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	_ = "STUB: not implemented"
	return *new(canoto.Writer)
}

const (
	canoto__Op__ID        = 1
	canoto__Op__Gas       = 2
	canoto__Op__GasFeeCap = 3
	canoto__Op__Burn      = 4
	canoto__Op__Mint      = 5

	canoto__Op__ID__tag        = "\x0a" // canoto.Tag(canoto__Op__ID, canoto.Len)
	canoto__Op__Gas__tag       = "\x10" // canoto.Tag(canoto__Op__Gas, canoto.Varint)
	canoto__Op__GasFeeCap__tag = "\x1a" // canoto.Tag(canoto__Op__GasFeeCap, canoto.Len)
	canoto__Op__Burn__tag      = "\x22" // canoto.Tag(canoto__Op__Burn, canoto.Len)
	canoto__Op__Mint__tag      = "\x2a" // canoto.Tag(canoto__Op__Mint, canoto.Len)
)

type canotoData_Op struct {
	size          uint64
	GasFeeCapSize uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*Op) CanotoSpec(types ...reflect.Type) *canoto.Spec { _ = "STUB: not implemented"; return nil }

/*type inference:*/
/*FieldNumber:   */
/*Name:          */
/*FixedLength:   */
/*Repeated:      */
/*OneOf:         */
/*Pointer:       */
/*types:         */

/*type inference:*/
/*FieldNumber:   */
/*Name:          */
/*FixedLength:   */
/*Repeated:      */
/*OneOf:         */
/*Pointer:       */
/*types:         */

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *Op) UnmarshalCanoto(bytes []byte) error { _ = "STUB: not implemented"; return nil }

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *Op) UnmarshalCanotoFrom(r canoto.Reader) error {
	_ = "STUB: not implemented"
	// Zero the struct before unmarshaling.
	return nil
}

// Read the packed field bytes.

// Read each value from the packed field bytes into the array.

// Read the first entry manually because the tag is already
// stripped.

// Count the number of additional entries after the first entry.

// Read the rest of the entries, stripping the tag each time.

// Read the first entry manually because the tag is already
// stripped.

// Count the number of additional entries after the first entry.

// Read the rest of the entries, stripping the tag each time.

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *Op) ValidCanoto() bool { _ = "STUB: not implemented"; return false }

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
//
// It is not safe to copy this struct concurrently.
func (c *Op) CalculateCanotoCache() { _ = "STUB: not implemented"; return }

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *Op) CachedCanotoSize() uint64 { _ = "STUB: not implemented"; return 0 }

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *Op) MarshalCanoto() []byte { _ = "STUB: not implemented"; return nil }

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *Op) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	_ = "STUB: not implemented"
	return *new(canoto.Writer)
}

const (
	canoto__AccountDebit__Address    = 1
	canoto__AccountDebit__Nonce      = 2
	canoto__AccountDebit__Amount     = 3
	canoto__AccountDebit__MinBalance = 4

	canoto__AccountDebit__Address__tag    = "\x0a" // canoto.Tag(canoto__AccountDebit__Address, canoto.Len)
	canoto__AccountDebit__Nonce__tag      = "\x10" // canoto.Tag(canoto__AccountDebit__Nonce, canoto.Varint)
	canoto__AccountDebit__Amount__tag     = "\x1a" // canoto.Tag(canoto__AccountDebit__Amount, canoto.Len)
	canoto__AccountDebit__MinBalance__tag = "\x22" // canoto.Tag(canoto__AccountDebit__MinBalance, canoto.Len)
)

type canotoData_AccountDebit struct {
	size           uint64
	AmountSize     uint64
	MinBalanceSize uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*AccountDebit) CanotoSpec(...reflect.Type) *canoto.Spec {
	_ = "STUB: not implemented"
	return nil
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *AccountDebit) UnmarshalCanoto(bytes []byte) error { _ = "STUB: not implemented"; return nil }

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *AccountDebit) UnmarshalCanotoFrom(r canoto.Reader) error {
	_ = "STUB: not implemented"
	// Zero the struct before unmarshaling.
	return nil
}

// Read the packed field bytes.

// Read each value from the packed field bytes into the array.

// Read the packed field bytes.

// Read each value from the packed field bytes into the array.

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *AccountDebit) ValidCanoto() bool {
	_ = "STUB: not implemented"

	// CalculateCanotoCache populates size and OneOf caches based on the current
	// values in the struct.
	//
	// It is not safe to copy this struct concurrently.
	return false
}

func (c *AccountDebit) CalculateCanotoCache() { _ = "STUB: not implemented"; return }

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *AccountDebit) CachedCanotoSize() uint64 { _ = "STUB: not implemented"; return 0 }

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AccountDebit) MarshalCanoto() []byte { _ = "STUB: not implemented"; return nil }

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AccountDebit) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	_ = "STUB: not implemented"
	return *new(canoto.Writer)
}

const (
	canoto__AccountCredit__Address = 1
	canoto__AccountCredit__Amount  = 2

	canoto__AccountCredit__Address__tag = "\x0a" // canoto.Tag(canoto__AccountCredit__Address, canoto.Len)
	canoto__AccountCredit__Amount__tag  = "\x12" // canoto.Tag(canoto__AccountCredit__Amount, canoto.Len)
)

type canotoData_AccountCredit struct {
	size       uint64
	AmountSize uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*AccountCredit) CanotoSpec(...reflect.Type) *canoto.Spec {
	_ = "STUB: not implemented"
	return nil
}

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *AccountCredit) UnmarshalCanoto(bytes []byte) error { _ = "STUB: not implemented"; return nil }

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *AccountCredit) UnmarshalCanotoFrom(r canoto.Reader) error {
	_ = "STUB: not implemented"
	// Zero the struct before unmarshaling.
	return nil
}

// Read the packed field bytes.

// Read each value from the packed field bytes into the array.

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *AccountCredit) ValidCanoto() bool {
	_ = "STUB: not implemented"

	// CalculateCanotoCache populates size and OneOf caches based on the current
	// values in the struct.
	//
	// It is not safe to copy this struct concurrently.
	return false
}

func (c *AccountCredit) CalculateCanotoCache() { _ = "STUB: not implemented"; return }

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *AccountCredit) CachedCanotoSize() uint64 { _ = "STUB: not implemented"; return 0 }

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AccountCredit) MarshalCanoto() []byte { _ = "STUB: not implemented"; return nil }

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
//
// It is not safe to copy this struct concurrently.
func (c *AccountCredit) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	_ = "STUB: not implemented"
	return *new(canoto.Writer)
}
