// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -package=contract -source=interfaces.go -destination=mocks.go -exclude_interfaces StatefulPrecompiledContract,StateReader,ConfigurationBlockContext,Configurator
//

// Package contract is a generated GoMock package.
package contract

import (
	big "math/big"

	precompileconfig "github.com/ava-labs/avalanchego/graft/coreth/precompile/precompileconfig"
	snow "github.com/ava-labs/avalanchego/snow"
	set "github.com/ava-labs/avalanchego/utils/set"
	predicate "github.com/ava-labs/avalanchego/vms/evm/predicate"
	common "github.com/ava-labs/libevm/common"
	types "github.com/ava-labs/libevm/core/types"
	vm "github.com/ava-labs/libevm/core/vm"
	stateconf "github.com/ava-labs/libevm/libevm/stateconf"
	uint256 "github.com/holiman/uint256"
	gomock "go.uber.org/mock/gomock"
)

// MockStateDB is a mock of StateDB interface.
type MockStateDB struct {
	ctrl     *gomock.Controller
	recorder *MockStateDBMockRecorder
	isgomock struct{}
}

// MockStateDBMockRecorder is the mock recorder for MockStateDB.
type MockStateDBMockRecorder struct {
	mock *MockStateDB
}

// NewMockStateDB creates a new mock instance.
func NewMockStateDB(ctrl *gomock.Controller) *MockStateDB { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateDB) EXPECT() *MockStateDBMockRecorder {
	_ = "STUB: not implemented"

	// AddBalance mocks base method.
	return nil
}

func (m *MockStateDB) AddBalance(arg0 common.Address, arg1 *uint256.Int) {
	_ = "STUB: not implemented"
	return
}

// AddBalance indicates an expected call of AddBalance.
func (mr *MockStateDBMockRecorder) AddBalance(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddBalanceMultiCoin mocks base method.
func (m *MockStateDB) AddBalanceMultiCoin(arg0 common.Address, arg1 common.Hash, arg2 *big.Int) {
	_ = "STUB: not implemented"
	return
}

// AddBalanceMultiCoin indicates an expected call of AddBalanceMultiCoin.
func (mr *MockStateDBMockRecorder) AddBalanceMultiCoin(arg0, arg1, arg2 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddLog mocks base method.
func (m *MockStateDB) AddLog(arg0 *types.Log) { _ = "STUB: not implemented"; return }

// AddLog indicates an expected call of AddLog.
func (mr *MockStateDBMockRecorder) AddLog(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateAccount mocks base method.
func (m *MockStateDB) CreateAccount(arg0 common.Address) { _ = "STUB: not implemented"; return }

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockStateDBMockRecorder) CreateAccount(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Exist mocks base method.
func (m *MockStateDB) Exist(arg0 common.Address) bool { _ = "STUB: not implemented"; return false }

// Exist indicates an expected call of Exist.
func (mr *MockStateDBMockRecorder) Exist(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBalance mocks base method.
func (m *MockStateDB) GetBalance(arg0 common.Address) *uint256.Int {
	_ = "STUB: not implemented"
	return nil
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockStateDBMockRecorder) GetBalance(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBalanceMultiCoin mocks base method.
func (m *MockStateDB) GetBalanceMultiCoin(arg0 common.Address, arg1 common.Hash) *big.Int {
	_ = "STUB: not implemented"
	return nil
}

// GetBalanceMultiCoin indicates an expected call of GetBalanceMultiCoin.
func (mr *MockStateDBMockRecorder) GetBalanceMultiCoin(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNonce mocks base method.
func (m *MockStateDB) GetNonce(arg0 common.Address) uint64 { _ = "STUB: not implemented"; return 0 }

// GetNonce indicates an expected call of GetNonce.
func (mr *MockStateDBMockRecorder) GetNonce(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetPredicate mocks base method.
func (m *MockStateDB) GetPredicate(address common.Address, index int) (predicate.Predicate, bool) {
	_ = "STUB: not implemented"
	return *new(predicate.Predicate), false
}

// GetPredicate indicates an expected call of GetPredicate.
func (mr *MockStateDBMockRecorder) GetPredicate(address, index any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetState mocks base method.
func (m *MockStateDB) GetState(arg0 common.Address, arg1 common.Hash, arg2 ...stateconf.StateDBStateOption) common.Hash {
	_ = "STUB: not implemented"
	return *new(common.Hash)
}

// GetState indicates an expected call of GetState.
func (mr *MockStateDBMockRecorder) GetState(arg0, arg1 any, arg2 ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Logs mocks base method.
func (m *MockStateDB) Logs() []*types.Log { _ = "STUB: not implemented"; return nil }

// Logs indicates an expected call of Logs.
func (mr *MockStateDBMockRecorder) Logs() *gomock.Call { _ = "STUB: not implemented"; return nil }

// RevertToSnapshot mocks base method.
func (m *MockStateDB) RevertToSnapshot(arg0 int) { _ = "STUB: not implemented"; return }

// RevertToSnapshot indicates an expected call of RevertToSnapshot.
func (mr *MockStateDBMockRecorder) RevertToSnapshot(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetNonce mocks base method.
func (m *MockStateDB) SetNonce(arg0 common.Address, arg1 uint64) { _ = "STUB: not implemented"; return }

// SetNonce indicates an expected call of SetNonce.
func (mr *MockStateDBMockRecorder) SetNonce(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetState mocks base method.
func (m *MockStateDB) SetState(arg0 common.Address, arg1, arg2 common.Hash, arg3 ...stateconf.StateDBStateOption) {
	_ = "STUB: not implemented"
	return
}

// SetState indicates an expected call of SetState.
func (mr *MockStateDBMockRecorder) SetState(arg0, arg1, arg2 any, arg3 ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Snapshot mocks base method.
func (m *MockStateDB) Snapshot() int { _ = "STUB: not implemented"; return 0 }

// Snapshot indicates an expected call of Snapshot.
func (mr *MockStateDBMockRecorder) Snapshot() *gomock.Call { _ = "STUB: not implemented"; return nil }

// SubBalanceMultiCoin mocks base method.
func (m *MockStateDB) SubBalanceMultiCoin(arg0 common.Address, arg1 common.Hash, arg2 *big.Int) {
	_ = "STUB: not implemented"
	return
}

// SubBalanceMultiCoin indicates an expected call of SubBalanceMultiCoin.
func (mr *MockStateDBMockRecorder) SubBalanceMultiCoin(arg0, arg1, arg2 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TxHash mocks base method.
func (m *MockStateDB) TxHash() common.Hash { _ = "STUB: not implemented"; return *new(common.Hash) }

// TxHash indicates an expected call of TxHash.
func (mr *MockStateDBMockRecorder) TxHash() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockAccessibleState is a mock of AccessibleState interface.
type MockAccessibleState struct {
	ctrl     *gomock.Controller
	recorder *MockAccessibleStateMockRecorder
	isgomock struct{}
}

// MockAccessibleStateMockRecorder is the mock recorder for MockAccessibleState.
type MockAccessibleStateMockRecorder struct {
	mock *MockAccessibleState
}

// NewMockAccessibleState creates a new mock instance.
func NewMockAccessibleState(ctrl *gomock.Controller) *MockAccessibleState {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessibleState) EXPECT() *MockAccessibleStateMockRecorder {
	_ = "STUB: not implemented"

	// GetBlockContext mocks base method.
	return nil
}

func (m *MockAccessibleState) GetBlockContext() BlockContext {
	_ = "STUB: not implemented"
	return *new(BlockContext)
}

// GetBlockContext indicates an expected call of GetBlockContext.
func (mr *MockAccessibleStateMockRecorder) GetBlockContext() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetPrecompileEnv mocks base method.
func (m *MockAccessibleState) GetPrecompileEnv() vm.PrecompileEnvironment {
	_ = "STUB: not implemented"
	return *new(vm.PrecompileEnvironment)
}

// GetPrecompileEnv indicates an expected call of GetPrecompileEnv.
func (mr *MockAccessibleStateMockRecorder) GetPrecompileEnv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetRules mocks base method.
func (m *MockAccessibleState) GetRules() precompileconfig.Rules {
	_ = "STUB: not implemented"
	return *new(precompileconfig.Rules)
}

// GetRules indicates an expected call of GetRules.
func (mr *MockAccessibleStateMockRecorder) GetRules() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSnowContext mocks base method.
func (m *MockAccessibleState) GetSnowContext() *snow.Context { _ = "STUB: not implemented"; return nil }

// GetSnowContext indicates an expected call of GetSnowContext.
func (mr *MockAccessibleStateMockRecorder) GetSnowContext() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetStateDB mocks base method.
func (m *MockAccessibleState) GetStateDB() StateDB { _ = "STUB: not implemented"; return *new(StateDB) }

// GetStateDB indicates an expected call of GetStateDB.
func (mr *MockAccessibleStateMockRecorder) GetStateDB() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockBlockContext is a mock of BlockContext interface.
type MockBlockContext struct {
	ctrl     *gomock.Controller
	recorder *MockBlockContextMockRecorder
	isgomock struct{}
}

// MockBlockContextMockRecorder is the mock recorder for MockBlockContext.
type MockBlockContextMockRecorder struct {
	mock *MockBlockContext
}

// NewMockBlockContext creates a new mock instance.
func NewMockBlockContext(ctrl *gomock.Controller) *MockBlockContext {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockContext) EXPECT() *MockBlockContextMockRecorder {
	_ = "STUB: not implemented"

	// GetPredicateResults mocks base method.
	return nil
}

func (m *MockBlockContext) GetPredicateResults(txHash common.Hash, precompileAddress common.Address) set.Bits {
	_ = "STUB: not implemented"
	return *new(set.Bits)
}

// GetPredicateResults indicates an expected call of GetPredicateResults.
func (mr *MockBlockContextMockRecorder) GetPredicateResults(txHash, precompileAddress any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Number mocks base method.
func (m *MockBlockContext) Number() *big.Int { _ = "STUB: not implemented"; return nil }

// Number indicates an expected call of Number.
func (mr *MockBlockContextMockRecorder) Number() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Timestamp mocks base method.
func (m *MockBlockContext) Timestamp() uint64 { _ = "STUB: not implemented"; return 0 }

// Timestamp indicates an expected call of Timestamp.
func (mr *MockBlockContextMockRecorder) Timestamp() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
