// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/snow/engine/snowman/block (interfaces: ChainVM)
//
// Generated by this command:
//
//	mockgen -package=blockmock -destination=blockmock/chain_vm.go -mock_names=ChainVM=ChainVM . ChainVM
//

// Package blockmock is a generated GoMock package.
package blockmock

import (
	context "context"
	http "net/http"
	time "time"

	database "github.com/ava-labs/avalanchego/database"
	ids "github.com/ava-labs/avalanchego/ids"
	snow "github.com/ava-labs/avalanchego/snow"
	snowman "github.com/ava-labs/avalanchego/snow/consensus/snowman"
	common "github.com/ava-labs/avalanchego/snow/engine/common"
	version "github.com/ava-labs/avalanchego/version"
	gomock "go.uber.org/mock/gomock"
)

// ChainVM is a mock of ChainVM interface.
type ChainVM struct {
	ctrl     *gomock.Controller
	recorder *ChainVMMockRecorder
	isgomock struct{}
}

// ChainVMMockRecorder is the mock recorder for ChainVM.
type ChainVMMockRecorder struct {
	mock *ChainVM
}

// NewChainVM creates a new mock instance.
func NewChainVM(ctrl *gomock.Controller) *ChainVM { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ChainVM) EXPECT() *ChainVMMockRecorder {
	_ = "STUB: not implemented"

	// AppGossip mocks base method.
	return nil
}

func (m *ChainVM) AppGossip(ctx context.Context, nodeID ids.NodeID, msg []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// AppGossip indicates an expected call of AppGossip.
func (mr *ChainVMMockRecorder) AppGossip(ctx, nodeID, msg any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AppRequest mocks base method.
func (m *ChainVM) AppRequest(ctx context.Context, nodeID ids.NodeID, requestID uint32, deadline time.Time, request []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// AppRequest indicates an expected call of AppRequest.
func (mr *ChainVMMockRecorder) AppRequest(ctx, nodeID, requestID, deadline, request any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AppRequestFailed mocks base method.
func (m *ChainVM) AppRequestFailed(ctx context.Context, nodeID ids.NodeID, requestID uint32, appErr *common.AppError) error {
	_ = "STUB: not implemented"
	return nil
}

// AppRequestFailed indicates an expected call of AppRequestFailed.
func (mr *ChainVMMockRecorder) AppRequestFailed(ctx, nodeID, requestID, appErr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AppResponse mocks base method.
func (m *ChainVM) AppResponse(ctx context.Context, nodeID ids.NodeID, requestID uint32, response []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// AppResponse indicates an expected call of AppResponse.
func (mr *ChainVMMockRecorder) AppResponse(ctx, nodeID, requestID, response any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BuildBlock mocks base method.
func (m *ChainVM) BuildBlock(arg0 context.Context) (snowman.Block, error) {
	_ = "STUB: not implemented"
	return *new(snowman.Block), nil
}

// BuildBlock indicates an expected call of BuildBlock.
func (mr *ChainVMMockRecorder) BuildBlock(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Connected mocks base method.
func (m *ChainVM) Connected(ctx context.Context, nodeID ids.NodeID, nodeVersion *version.Application) error {
	_ = "STUB: not implemented"
	return nil
}

// Connected indicates an expected call of Connected.
func (mr *ChainVMMockRecorder) Connected(ctx, nodeID, nodeVersion any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateHandlers mocks base method.
func (m *ChainVM) CreateHandlers(arg0 context.Context) (map[string]http.Handler, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateHandlers indicates an expected call of CreateHandlers.
func (mr *ChainVMMockRecorder) CreateHandlers(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Disconnected mocks base method.
func (m *ChainVM) Disconnected(ctx context.Context, nodeID ids.NodeID) error {
	_ = "STUB: not implemented"
	return nil
}

// Disconnected indicates an expected call of Disconnected.
func (mr *ChainVMMockRecorder) Disconnected(ctx, nodeID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBlock mocks base method.
func (m *ChainVM) GetBlock(ctx context.Context, blkID ids.ID) (snowman.Block, error) {
	_ = "STUB: not implemented"
	return *new(snowman.Block), nil
}

// GetBlock indicates an expected call of GetBlock.
func (mr *ChainVMMockRecorder) GetBlock(ctx, blkID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBlockIDAtHeight mocks base method.
func (m *ChainVM) GetBlockIDAtHeight(ctx context.Context, height uint64) (ids.ID, error) {
	_ = "STUB: not implemented"
	return *new(ids.ID), nil
}

// GetBlockIDAtHeight indicates an expected call of GetBlockIDAtHeight.
func (mr *ChainVMMockRecorder) GetBlockIDAtHeight(ctx, height any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HealthCheck mocks base method.
func (m *ChainVM) HealthCheck(arg0 context.Context) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *ChainVMMockRecorder) HealthCheck(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Initialize mocks base method.
func (m *ChainVM) Initialize(ctx context.Context, chainCtx *snow.Context, db database.Database, genesisBytes, upgradeBytes, configBytes []byte, fxs []*common.Fx, appSender common.AppSender) error {
	_ = "STUB: not implemented"
	return nil
}

// Initialize indicates an expected call of Initialize.
func (mr *ChainVMMockRecorder) Initialize(ctx, chainCtx, db, genesisBytes, upgradeBytes, configBytes, fxs, appSender any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LastAccepted mocks base method.
func (m *ChainVM) LastAccepted(arg0 context.Context) (ids.ID, error) {
	_ = "STUB: not implemented"
	return *new(ids.ID), nil
}

// LastAccepted indicates an expected call of LastAccepted.
func (mr *ChainVMMockRecorder) LastAccepted(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewHTTPHandler mocks base method.
func (m *ChainVM) NewHTTPHandler(ctx context.Context) (http.Handler, error) {
	_ = "STUB: not implemented"
	return *new(http.Handler), nil
}

// NewHTTPHandler indicates an expected call of NewHTTPHandler.
func (mr *ChainVMMockRecorder) NewHTTPHandler(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ParseBlock mocks base method.
func (m *ChainVM) ParseBlock(ctx context.Context, blockBytes []byte) (snowman.Block, error) {
	_ = "STUB: not implemented"
	return *new(snowman.Block), nil
}

// ParseBlock indicates an expected call of ParseBlock.
func (mr *ChainVMMockRecorder) ParseBlock(ctx, blockBytes any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetPreference mocks base method.
func (m *ChainVM) SetPreference(ctx context.Context, blkID ids.ID) error {
	_ = "STUB: not implemented"
	return nil
}

// SetPreference indicates an expected call of SetPreference.
func (mr *ChainVMMockRecorder) SetPreference(ctx, blkID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetState mocks base method.
func (m *ChainVM) SetState(ctx context.Context, state snow.State) error {
	_ = "STUB: not implemented"
	return nil
}

// SetState indicates an expected call of SetState.
func (mr *ChainVMMockRecorder) SetState(ctx, state any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Shutdown mocks base method.
func (m *ChainVM) Shutdown(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Shutdown indicates an expected call of Shutdown.
func (mr *ChainVMMockRecorder) Shutdown(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Version mocks base method.
func (m *ChainVM) Version(arg0 context.Context) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// Version indicates an expected call of Version.
func (mr *ChainVMMockRecorder) Version(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WaitForEvent mocks base method.
func (m *ChainVM) WaitForEvent(ctx context.Context) (common.Message, error) {
	_ = "STUB: not implemented"
	return *new(common.Message), nil
}

// WaitForEvent indicates an expected call of WaitForEvent.
func (mr *ChainVMMockRecorder) WaitForEvent(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
