// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/snow/engine/snowman/block (interfaces: FullVM)
//
// Generated by this command:
//
//	mockgen -package=blockmock -destination=blockmock/full_vm.go -mock_names=FullVM=FullVM . FullVM
//

// Package blockmock is a generated GoMock package.
package blockmock

import (
	context "context"
	http "net/http"
	time "time"

	database "github.com/ava-labs/avalanchego/database"
	ids "github.com/ava-labs/avalanchego/ids"
	snow "github.com/ava-labs/avalanchego/snow"
	snowman "github.com/ava-labs/avalanchego/snow/consensus/snowman"
	common "github.com/ava-labs/avalanchego/snow/engine/common"
	block "github.com/ava-labs/avalanchego/snow/engine/snowman/block"
	version "github.com/ava-labs/avalanchego/version"
	gomock "go.uber.org/mock/gomock"
)

// FullVM is a mock of FullVM interface.
type FullVM struct {
	ctrl     *gomock.Controller
	recorder *FullVMMockRecorder
	isgomock struct{}
}

// FullVMMockRecorder is the mock recorder for FullVM.
type FullVMMockRecorder struct {
	mock *FullVM
}

// NewFullVM creates a new mock instance.
func NewFullVM(ctrl *gomock.Controller) *FullVM { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *FullVM) EXPECT() *FullVMMockRecorder {
	_ = "STUB: not implemented"

	// AppGossip mocks base method.
	return nil
}

func (m *FullVM) AppGossip(ctx context.Context, nodeID ids.NodeID, msg []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// AppGossip indicates an expected call of AppGossip.
func (mr *FullVMMockRecorder) AppGossip(ctx, nodeID, msg any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AppRequest mocks base method.
func (m *FullVM) AppRequest(ctx context.Context, nodeID ids.NodeID, requestID uint32, deadline time.Time, request []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// AppRequest indicates an expected call of AppRequest.
func (mr *FullVMMockRecorder) AppRequest(ctx, nodeID, requestID, deadline, request any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AppRequestFailed mocks base method.
func (m *FullVM) AppRequestFailed(ctx context.Context, nodeID ids.NodeID, requestID uint32, appErr *common.AppError) error {
	_ = "STUB: not implemented"
	return nil
}

// AppRequestFailed indicates an expected call of AppRequestFailed.
func (mr *FullVMMockRecorder) AppRequestFailed(ctx, nodeID, requestID, appErr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AppResponse mocks base method.
func (m *FullVM) AppResponse(ctx context.Context, nodeID ids.NodeID, requestID uint32, response []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// AppResponse indicates an expected call of AppResponse.
func (mr *FullVMMockRecorder) AppResponse(ctx, nodeID, requestID, response any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BatchedParseBlock mocks base method.
func (m *FullVM) BatchedParseBlock(ctx context.Context, blks [][]byte) ([]snowman.Block, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// BatchedParseBlock indicates an expected call of BatchedParseBlock.
func (mr *FullVMMockRecorder) BatchedParseBlock(ctx, blks any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BuildBlock mocks base method.
func (m *FullVM) BuildBlock(arg0 context.Context) (snowman.Block, error) {
	_ = "STUB: not implemented"
	return *new(snowman.Block), nil
}

// BuildBlock indicates an expected call of BuildBlock.
func (mr *FullVMMockRecorder) BuildBlock(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Connected mocks base method.
func (m *FullVM) Connected(ctx context.Context, nodeID ids.NodeID, nodeVersion *version.Application) error {
	_ = "STUB: not implemented"
	return nil
}

// Connected indicates an expected call of Connected.
func (mr *FullVMMockRecorder) Connected(ctx, nodeID, nodeVersion any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateHandlers mocks base method.
func (m *FullVM) CreateHandlers(arg0 context.Context) (map[string]http.Handler, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateHandlers indicates an expected call of CreateHandlers.
func (mr *FullVMMockRecorder) CreateHandlers(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Disconnected mocks base method.
func (m *FullVM) Disconnected(ctx context.Context, nodeID ids.NodeID) error {
	_ = "STUB: not implemented"
	return nil
}

// Disconnected indicates an expected call of Disconnected.
func (mr *FullVMMockRecorder) Disconnected(ctx, nodeID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetAncestors mocks base method.
func (m *FullVM) GetAncestors(ctx context.Context, blkID ids.ID, maxBlocksNum, maxBlocksSize int, maxBlocksRetrivalTime time.Duration) ([][]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAncestors indicates an expected call of GetAncestors.
func (mr *FullVMMockRecorder) GetAncestors(ctx, blkID, maxBlocksNum, maxBlocksSize, maxBlocksRetrivalTime any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBlock mocks base method.
func (m *FullVM) GetBlock(ctx context.Context, blkID ids.ID) (snowman.Block, error) {
	_ = "STUB: not implemented"
	return *new(snowman.Block), nil
}

// GetBlock indicates an expected call of GetBlock.
func (mr *FullVMMockRecorder) GetBlock(ctx, blkID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBlockIDAtHeight mocks base method.
func (m *FullVM) GetBlockIDAtHeight(ctx context.Context, height uint64) (ids.ID, error) {
	_ = "STUB: not implemented"
	return *new(ids.ID), nil
}

// GetBlockIDAtHeight indicates an expected call of GetBlockIDAtHeight.
func (mr *FullVMMockRecorder) GetBlockIDAtHeight(ctx, height any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLastStateSummary mocks base method.
func (m *FullVM) GetLastStateSummary(arg0 context.Context) (block.StateSummary, error) {
	_ = "STUB: not implemented"
	return *new(block.StateSummary), nil
}

// GetLastStateSummary indicates an expected call of GetLastStateSummary.
func (mr *FullVMMockRecorder) GetLastStateSummary(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetOngoingSyncStateSummary mocks base method.
func (m *FullVM) GetOngoingSyncStateSummary(arg0 context.Context) (block.StateSummary, error) {
	_ = "STUB: not implemented"
	return *new(block.StateSummary), nil
}

// GetOngoingSyncStateSummary indicates an expected call of GetOngoingSyncStateSummary.
func (mr *FullVMMockRecorder) GetOngoingSyncStateSummary(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetStateSummary mocks base method.
func (m *FullVM) GetStateSummary(ctx context.Context, summaryHeight uint64) (block.StateSummary, error) {
	_ = "STUB: not implemented"
	return *new(block.StateSummary), nil
}

// GetStateSummary indicates an expected call of GetStateSummary.
func (mr *FullVMMockRecorder) GetStateSummary(ctx, summaryHeight any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HealthCheck mocks base method.
func (m *FullVM) HealthCheck(arg0 context.Context) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *FullVMMockRecorder) HealthCheck(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Initialize mocks base method.
func (m *FullVM) Initialize(ctx context.Context, chainCtx *snow.Context, db database.Database, genesisBytes, upgradeBytes, configBytes []byte, fxs []*common.Fx, appSender common.AppSender) error {
	_ = "STUB: not implemented"
	return nil
}

// Initialize indicates an expected call of Initialize.
func (mr *FullVMMockRecorder) Initialize(ctx, chainCtx, db, genesisBytes, upgradeBytes, configBytes, fxs, appSender any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LastAccepted mocks base method.
func (m *FullVM) LastAccepted(arg0 context.Context) (ids.ID, error) {
	_ = "STUB: not implemented"
	return *new(ids.ID), nil
}

// LastAccepted indicates an expected call of LastAccepted.
func (mr *FullVMMockRecorder) LastAccepted(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewHTTPHandler mocks base method.
func (m *FullVM) NewHTTPHandler(ctx context.Context) (http.Handler, error) {
	_ = "STUB: not implemented"
	return *new(http.Handler), nil
}

// NewHTTPHandler indicates an expected call of NewHTTPHandler.
func (mr *FullVMMockRecorder) NewHTTPHandler(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ParseBlock mocks base method.
func (m *FullVM) ParseBlock(ctx context.Context, blockBytes []byte) (snowman.Block, error) {
	_ = "STUB: not implemented"
	return *new(snowman.Block), nil
}

// ParseBlock indicates an expected call of ParseBlock.
func (mr *FullVMMockRecorder) ParseBlock(ctx, blockBytes any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ParseStateSummary mocks base method.
func (m *FullVM) ParseStateSummary(ctx context.Context, summaryBytes []byte) (block.StateSummary, error) {
	_ = "STUB: not implemented"
	return *new(block.StateSummary), nil
}

// ParseStateSummary indicates an expected call of ParseStateSummary.
func (mr *FullVMMockRecorder) ParseStateSummary(ctx, summaryBytes any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetPreference mocks base method.
func (m *FullVM) SetPreference(ctx context.Context, blkID ids.ID) error {
	_ = "STUB: not implemented"
	return nil
}

// SetPreference indicates an expected call of SetPreference.
func (mr *FullVMMockRecorder) SetPreference(ctx, blkID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetState mocks base method.
func (m *FullVM) SetState(ctx context.Context, state snow.State) error {
	_ = "STUB: not implemented"
	return nil
}

// SetState indicates an expected call of SetState.
func (mr *FullVMMockRecorder) SetState(ctx, state any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Shutdown mocks base method.
func (m *FullVM) Shutdown(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Shutdown indicates an expected call of Shutdown.
func (mr *FullVMMockRecorder) Shutdown(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StateSyncEnabled mocks base method.
func (m *FullVM) StateSyncEnabled(arg0 context.Context) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// StateSyncEnabled indicates an expected call of StateSyncEnabled.
func (mr *FullVMMockRecorder) StateSyncEnabled(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Version mocks base method.
func (m *FullVM) Version(arg0 context.Context) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// Version indicates an expected call of Version.
func (mr *FullVMMockRecorder) Version(arg0 any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// WaitForEvent mocks base method.
func (m *FullVM) WaitForEvent(ctx context.Context) (common.Message, error) {
	_ = "STUB: not implemented"
	return *new(common.Message), nil
}

// WaitForEvent indicates an expected call of WaitForEvent.
func (mr *FullVMMockRecorder) WaitForEvent(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
