// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/snow/engine/snowman/block (interfaces: StateSyncableVM)
//
// Generated by this command:
//
//	mockgen -package=blockmock -destination=blockmock/state_syncable_vm.go -mock_names=StateSyncableVM=StateSyncableVM . StateSyncableVM
//

// Package blockmock is a generated GoMock package.
package blockmock

import (
	context "context"

	block "github.com/ava-labs/avalanchego/snow/engine/snowman/block"
	gomock "go.uber.org/mock/gomock"
)

// StateSyncableVM is a mock of StateSyncableVM interface.
type StateSyncableVM struct {
	ctrl     *gomock.Controller
	recorder *StateSyncableVMMockRecorder
	isgomock struct{}
}

// StateSyncableVMMockRecorder is the mock recorder for StateSyncableVM.
type StateSyncableVMMockRecorder struct {
	mock *StateSyncableVM
}

// NewStateSyncableVM creates a new mock instance.
func NewStateSyncableVM(ctrl *gomock.Controller) *StateSyncableVM {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *StateSyncableVM) EXPECT() *StateSyncableVMMockRecorder {
	_ = "STUB: not implemented"

	// GetLastStateSummary mocks base method.
	return nil
}

func (m *StateSyncableVM) GetLastStateSummary(arg0 context.Context) (block.StateSummary, error) {
	_ = "STUB: not implemented"
	return *new(block.StateSummary), nil
}

// GetLastStateSummary indicates an expected call of GetLastStateSummary.
func (mr *StateSyncableVMMockRecorder) GetLastStateSummary(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetOngoingSyncStateSummary mocks base method.
func (m *StateSyncableVM) GetOngoingSyncStateSummary(arg0 context.Context) (block.StateSummary, error) {
	_ = "STUB: not implemented"
	return *new(block.StateSummary), nil
}

// GetOngoingSyncStateSummary indicates an expected call of GetOngoingSyncStateSummary.
func (mr *StateSyncableVMMockRecorder) GetOngoingSyncStateSummary(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetStateSummary mocks base method.
func (m *StateSyncableVM) GetStateSummary(ctx context.Context, summaryHeight uint64) (block.StateSummary, error) {
	_ = "STUB: not implemented"
	return *new(block.StateSummary), nil
}

// GetStateSummary indicates an expected call of GetStateSummary.
func (mr *StateSyncableVMMockRecorder) GetStateSummary(ctx, summaryHeight any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ParseStateSummary mocks base method.
func (m *StateSyncableVM) ParseStateSummary(ctx context.Context, summaryBytes []byte) (block.StateSummary, error) {
	_ = "STUB: not implemented"
	return *new(block.StateSummary), nil
}

// ParseStateSummary indicates an expected call of ParseStateSummary.
func (mr *StateSyncableVMMockRecorder) ParseStateSummary(ctx, summaryBytes any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// StateSyncEnabled mocks base method.
func (m *StateSyncableVM) StateSyncEnabled(arg0 context.Context) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// StateSyncEnabled indicates an expected call of StateSyncEnabled.
func (mr *StateSyncableVMMockRecorder) StateSyncEnabled(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
