// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/snow/engine/snowman/block (interfaces: WithVerifyContext)
//
// Generated by this command:
//
//	mockgen -package=blockmock -destination=blockmock/with_verify_context.go -mock_names=WithVerifyContext=WithVerifyContext . WithVerifyContext
//

// Package blockmock is a generated GoMock package.
package blockmock

import (
	context "context"

	block "github.com/ava-labs/avalanchego/snow/engine/snowman/block"
	gomock "go.uber.org/mock/gomock"
)

// WithVerifyContext is a mock of WithVerifyContext interface.
type WithVerifyContext struct {
	ctrl     *gomock.Controller
	recorder *WithVerifyContextMockRecorder
	isgomock struct{}
}

// WithVerifyContextMockRecorder is the mock recorder for WithVerifyContext.
type WithVerifyContextMockRecorder struct {
	mock *WithVerifyContext
}

// NewWithVerifyContext creates a new mock instance.
func NewWithVerifyContext(ctrl *gomock.Controller) *WithVerifyContext {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *WithVerifyContext) EXPECT() *WithVerifyContextMockRecorder {
	_ = "STUB: not implemented"

	// ShouldVerifyWithContext mocks base method.
	return nil
}

func (m *WithVerifyContext) ShouldVerifyWithContext(arg0 context.Context) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// ShouldVerifyWithContext indicates an expected call of ShouldVerifyWithContext.
func (mr *WithVerifyContextMockRecorder) ShouldVerifyWithContext(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// VerifyWithContext mocks base method.
func (m *WithVerifyContext) VerifyWithContext(arg0 context.Context, arg1 *block.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// VerifyWithContext indicates an expected call of VerifyWithContext.
func (mr *WithVerifyContextMockRecorder) VerifyWithContext(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
