// Code generated by canoto. DO NOT EDIT.
// versions:
// 	canoto v0.18.0
// source: gastime.go

package gastime

import (
	"io"
	"reflect"
	"sync/atomic"

	"github.com/StephenButtolph/canoto"
)

// Ensure that the generated code is compatible with the library version.
const (
	_ uint = canoto.VersionCompatibility - 1
	_ uint = 1 - canoto.VersionCompatibility
)

// Ensure that unused imports do not error
var (
	_ atomic.Uint64

	_ = io.ErrUnexpectedEOF
)

const (
	canoto__Time__Time   = 1
	canoto__Time__target = 2
	canoto__Time__excess = 3
	canoto__Time__config = 4

	canoto__Time__Time__tag   = "\x0a" // canoto.Tag(canoto__Time__Time, canoto.Len)
	canoto__Time__target__tag = "\x10" // canoto.Tag(canoto__Time__target, canoto.Varint)
	canoto__Time__excess__tag = "\x18" // canoto.Tag(canoto__Time__excess, canoto.Varint)
	canoto__Time__config__tag = "\x22" // canoto.Tag(canoto__Time__config, canoto.Len)
)

type canotoData_Time struct {
	size atomic.Uint64
}

// CanotoSpec returns the specification of this canoto message.
func (*Time) CanotoSpec(types ...reflect.Type) *canoto.Spec { _ = "STUB: not implemented"; return nil }

/*type inference:*/
/*FieldNumber:   */
/*Name:          */
/*FixedLength:   */
/*Repeated:      */
/*OneOf:         */
/*Pointer:       */
/*types:         */

/*type inference:*/
/*FieldNumber:   */
/*Name:          */
/*FixedLength:   */
/*Repeated:      */
/*OneOf:         */
/*Pointer:       */
/*types:         */

// UnmarshalCanoto unmarshals a Canoto-encoded byte slice into the struct.
//
// During parsing, the canoto cache is saved.
func (c *Time) UnmarshalCanoto(bytes []byte) error { _ = "STUB: not implemented"; return nil }

// UnmarshalCanotoFrom populates the struct from a [canoto.Reader]. Most users
// should just use UnmarshalCanoto.
//
// During parsing, the canoto cache is saved.
//
// This function enables configuration of reader options.
func (c *Time) UnmarshalCanotoFrom(r canoto.Reader) error {
	_ = "STUB: not implemented"
	// Zero the struct before unmarshaling.
	return nil
}

// Read the bytes for the field.

// Unmarshal the field from the bytes.

// Read the bytes for the field.

// Unmarshal the field from the bytes.

// ValidCanoto validates that the struct can be correctly marshaled into the
// Canoto format.
//
// Specifically, ValidCanoto ensures:
// 1. All OneOfs are specified at most once.
// 2. All strings are valid utf-8.
// 3. All custom fields are ValidCanoto.
func (c *Time) ValidCanoto() bool { _ = "STUB: not implemented"; return false }

// CalculateCanotoCache populates size and OneOf caches based on the current
// values in the struct.
func (c *Time) CalculateCanotoCache() { _ = "STUB: not implemented"; return }

// CachedCanotoSize returns the previously calculated size of the Canoto
// representation from CalculateCanotoCache.
//
// If CalculateCanotoCache has not yet been called, it will return 0.
//
// If the struct has been modified since the last call to CalculateCanotoCache,
// the returned size may be incorrect.
func (c *Time) CachedCanotoSize() uint64 { _ = "STUB: not implemented"; return 0 }

// MarshalCanoto returns the Canoto representation of this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *Time) MarshalCanoto() []byte { _ = "STUB: not implemented"; return nil }

// MarshalCanotoInto writes the struct into a [canoto.Writer] and returns the
// resulting [canoto.Writer]. Most users should just use MarshalCanoto.
//
// It is assumed that CalculateCanotoCache has been called since the last
// modification to this struct.
//
// It is assumed that this struct is ValidCanoto.
func (c *Time) MarshalCanotoInto(w canoto.Writer) canoto.Writer {
	_ = "STUB: not implemented"
	return *new(canoto.Writer)
}
