// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/snow/networking/handler (interfaces: Handler)
//
// Generated by this command:
//
//	mockgen -package=handlermock -destination=handlermock/handler.go -mock_names=Handler=Handler . Handler
//

// Package handlermock is a generated GoMock package.
package handlermock

import (
	context "context"
	time "time"

	ids "github.com/ava-labs/avalanchego/ids"
	snow "github.com/ava-labs/avalanchego/snow"
	handler "github.com/ava-labs/avalanchego/snow/networking/handler"
	gomock "go.uber.org/mock/gomock"
)

// Handler is a mock of Handler interface.
type Handler struct {
	ctrl     *gomock.Controller
	recorder *HandlerMockRecorder
	isgomock struct{}
}

// HandlerMockRecorder is the mock recorder for Handler.
type HandlerMockRecorder struct {
	mock *Handler
}

// NewHandler creates a new mock instance.
func NewHandler(ctrl *gomock.Controller) *Handler { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Handler) EXPECT() *HandlerMockRecorder {
	_ = "STUB: not implemented"

	// AwaitStopped mocks base method.
	return nil
}

func (m *Handler) AwaitStopped(ctx context.Context) (time.Duration, error) {
	_ = "STUB: not implemented"
	return *new(time.Duration), nil
}

// AwaitStopped indicates an expected call of AwaitStopped.
func (mr *HandlerMockRecorder) AwaitStopped(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Context mocks base method.
func (m *Handler) Context() *snow.ConsensusContext { _ = "STUB: not implemented"; return nil }

// Context indicates an expected call of Context.
func (mr *HandlerMockRecorder) Context() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetEngineManager mocks base method.
func (m *Handler) GetEngineManager() *handler.EngineManager { _ = "STUB: not implemented"; return nil }

// GetEngineManager indicates an expected call of GetEngineManager.
func (mr *HandlerMockRecorder) GetEngineManager() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HealthCheck mocks base method.
func (m *Handler) HealthCheck(arg0 context.Context) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *HandlerMockRecorder) HealthCheck(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Len mocks base method.
func (m *Handler) Len() int { _ = "STUB: not implemented"; return 0 }

// Len indicates an expected call of Len.
func (mr *HandlerMockRecorder) Len() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Push mocks base method.
func (m *Handler) Push(ctx context.Context, msg handler.Message) { _ = "STUB: not implemented"; return }

// Push indicates an expected call of Push.
func (mr *HandlerMockRecorder) Push(ctx, msg any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetEngineManager mocks base method.
func (m *Handler) SetEngineManager(engineManager *handler.EngineManager) {
	_ = "STUB: not implemented"
	return
}

// SetEngineManager indicates an expected call of SetEngineManager.
func (mr *HandlerMockRecorder) SetEngineManager(engineManager any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetOnStopped mocks base method.
func (m *Handler) SetOnStopped(onStopped func()) { _ = "STUB: not implemented"; return }

// SetOnStopped indicates an expected call of SetOnStopped.
func (mr *HandlerMockRecorder) SetOnStopped(onStopped any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ShouldHandle mocks base method.
func (m *Handler) ShouldHandle(nodeID ids.NodeID) bool { _ = "STUB: not implemented"; return false }

// ShouldHandle indicates an expected call of ShouldHandle.
func (mr *HandlerMockRecorder) ShouldHandle(nodeID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Start mocks base method.
func (m *Handler) Start(ctx context.Context, recoverPanic bool) { _ = "STUB: not implemented"; return }

// Start indicates an expected call of Start.
func (mr *HandlerMockRecorder) Start(ctx, recoverPanic any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *Handler) Stop(ctx context.Context) { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *HandlerMockRecorder) Stop(ctx any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// StopWithError mocks base method.
func (m *Handler) StopWithError(ctx context.Context, err error) { _ = "STUB: not implemented"; return }

// StopWithError indicates an expected call of StopWithError.
func (mr *HandlerMockRecorder) StopWithError(ctx, err any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
