// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/database (interfaces: Batch)
//
// Generated by this command:
//
//	mockgen -package=databasemock -destination=databasemock/batch.go -mock_names=Batch=Batch . Batch
//

// Package databasemock is a generated GoMock package.
package databasemock

import (
	database "github.com/ava-labs/avalanchego/database"
	gomock "go.uber.org/mock/gomock"
)

// Batch is a mock of Batch interface.
type Batch struct {
	ctrl     *gomock.Controller
	recorder *BatchMockRecorder
	isgomock struct{}
}

// BatchMockRecorder is the mock recorder for Batch.
type BatchMockRecorder struct {
	mock *Batch
}

// NewBatch creates a new mock instance.
func NewBatch(ctrl *gomock.Controller) *Batch { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Batch) EXPECT() *BatchMockRecorder {
	_ = "STUB: not implemented"

	// Delete mocks base method.
	return nil
}

func (m *Batch) Delete(key []byte) error { _ = "STUB: not implemented"; return nil }

// Delete indicates an expected call of Delete.
func (mr *BatchMockRecorder) Delete(key any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// Inner mocks base method.
func (m *Batch) Inner() database.Batch { _ = "STUB: not implemented"; return *new(database.Batch) }

// Inner indicates an expected call of Inner.
func (mr *BatchMockRecorder) Inner() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Put mocks base method.
func (m *Batch) Put(key, value []byte) error { _ = "STUB: not implemented"; return nil }

// Put indicates an expected call of Put.
func (mr *BatchMockRecorder) Put(key, value any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Replay mocks base method.
func (m *Batch) Replay(w database.KeyValueWriterDeleter) error {
	_ = "STUB: not implemented"
	return nil
}

// Replay indicates an expected call of Replay.
func (mr *BatchMockRecorder) Replay(w any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// Reset mocks base method.
func (m *Batch) Reset() { _ = "STUB: not implemented"; return }

// Reset indicates an expected call of Reset.
func (mr *BatchMockRecorder) Reset() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Size mocks base method.
func (m *Batch) Size() int { _ = "STUB: not implemented"; return 0 }

// Size indicates an expected call of Size.
func (mr *BatchMockRecorder) Size() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Write mocks base method.
func (m *Batch) Write() error { _ = "STUB: not implemented"; return nil }

// Write indicates an expected call of Write.
func (mr *BatchMockRecorder) Write() *gomock.Call { _ = "STUB: not implemented"; return nil }
