// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/database (interfaces: Iterator)
//
// Generated by this command:
//
//	mockgen -package=databasemock -destination=databasemock/iterator.go -mock_names=Iterator=Iterator . Iterator
//

// Package databasemock is a generated GoMock package.
package databasemock

import (
	gomock "go.uber.org/mock/gomock"
)

// Iterator is a mock of Iterator interface.
type Iterator struct {
	ctrl     *gomock.Controller
	recorder *IteratorMockRecorder
	isgomock struct{}
}

// IteratorMockRecorder is the mock recorder for Iterator.
type IteratorMockRecorder struct {
	mock *Iterator
}

// NewIterator creates a new mock instance.
func NewIterator(ctrl *gomock.Controller) *Iterator { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Iterator) EXPECT() *IteratorMockRecorder {
	_ = "STUB: not implemented"

	// Error mocks base method.
	return nil
}

func (m *Iterator) Error() error { _ = "STUB: not implemented"; return nil }

// Error indicates an expected call of Error.
func (mr *IteratorMockRecorder) Error() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Key mocks base method.
func (m *Iterator) Key() []byte { _ = "STUB: not implemented"; return nil }

// Key indicates an expected call of Key.
func (mr *IteratorMockRecorder) Key() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Next mocks base method.
func (m *Iterator) Next() bool { _ = "STUB: not implemented"; return false }

// Next indicates an expected call of Next.
func (mr *IteratorMockRecorder) Next() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Release mocks base method.
func (m *Iterator) Release() { _ = "STUB: not implemented"; return }

// Release indicates an expected call of Release.
func (mr *IteratorMockRecorder) Release() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Value mocks base method.
func (m *Iterator) Value() []byte { _ = "STUB: not implemented"; return nil }

// Value indicates an expected call of Value.
func (mr *IteratorMockRecorder) Value() *gomock.Call { _ = "STUB: not implemented"; return nil }
