// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/vms/platformvm/block (interfaces: Block)
//
// Generated by this command:
//
//	mockgen -package=block -destination=mock_block.go . Block
//

// Package block is a generated GoMock package.
package block

import (
	ids "github.com/ava-labs/avalanchego/ids"
	snow "github.com/ava-labs/avalanchego/snow"
	txs "github.com/ava-labs/avalanchego/vms/platformvm/txs"
	gomock "go.uber.org/mock/gomock"
)

// MockBlock is a mock of Block interface.
type MockBlock struct {
	ctrl     *gomock.Controller
	recorder *MockBlockMockRecorder
	isgomock struct{}
}

// MockBlockMockRecorder is the mock recorder for MockBlock.
type MockBlockMockRecorder struct {
	mock *MockBlock
}

// NewMockBlock creates a new mock instance.
func NewMockBlock(ctrl *gomock.Controller) *MockBlock { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlock) EXPECT() *MockBlockMockRecorder {
	_ = "STUB: not implemented"

	// Bytes mocks base method.
	return nil
}

func (m *MockBlock) Bytes() []byte { _ = "STUB: not implemented"; return nil }

// Bytes indicates an expected call of Bytes.
func (mr *MockBlockMockRecorder) Bytes() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Height mocks base method.
func (m *MockBlock) Height() uint64 { _ = "STUB: not implemented"; return 0 }

// Height indicates an expected call of Height.
func (mr *MockBlockMockRecorder) Height() *gomock.Call { _ = "STUB: not implemented"; return nil }

// ID mocks base method.
func (m *MockBlock) ID() ids.ID { _ = "STUB: not implemented"; return *new(ids.ID) }

// ID indicates an expected call of ID.
func (mr *MockBlockMockRecorder) ID() *gomock.Call { _ = "STUB: not implemented"; return nil }

// InitCtx mocks base method.
func (m *MockBlock) InitCtx(ctx *snow.Context) { _ = "STUB: not implemented"; return }

// InitCtx indicates an expected call of InitCtx.
func (mr *MockBlockMockRecorder) InitCtx(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Parent mocks base method.
func (m *MockBlock) Parent() ids.ID { _ = "STUB: not implemented"; return *new(ids.ID) }

// Parent indicates an expected call of Parent.
func (mr *MockBlockMockRecorder) Parent() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Txs mocks base method.
func (m *MockBlock) Txs() []*txs.Tx { _ = "STUB: not implemented"; return nil }

// Txs indicates an expected call of Txs.
func (mr *MockBlockMockRecorder) Txs() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Visit mocks base method.
func (m *MockBlock) Visit(visitor Visitor) error { _ = "STUB: not implemented"; return nil }

// Visit indicates an expected call of Visit.
func (mr *MockBlockMockRecorder) Visit(visitor any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// initialize mocks base method.
func (m *MockBlock) initialize(bytes []byte) error { _ = "STUB: not implemented"; return nil }

// initialize indicates an expected call of initialize.
func (mr *MockBlockMockRecorder) initialize(bytes any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
