// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sharedmemory/sharedmemory.proto

package sharedmemory

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchPut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPut) Reset() { _ = "STUB: not implemented"; return }

func (x *BatchPut) String() string { _ = "STUB: not implemented"; return "" }

func (*BatchPut) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *BatchPut) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use BatchPut.ProtoReflect.Descriptor instead.
func (*BatchPut) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *BatchPut) GetKey() []byte { _ = "STUB: not implemented"; return nil }

func (x *BatchPut) GetValue() []byte { _ = "STUB: not implemented"; return nil }

type BatchDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDelete) Reset() { _ = "STUB: not implemented"; return }

func (x *BatchDelete) String() string { _ = "STUB: not implemented"; return "" }

func (*BatchDelete) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *BatchDelete) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use BatchDelete.ProtoReflect.Descriptor instead.
func (*BatchDelete) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *BatchDelete) GetKey() []byte { _ = "STUB: not implemented"; return nil }

type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Puts          []*BatchPut            `protobuf:"bytes,1,rep,name=puts,proto3" json:"puts,omitempty"`
	Deletes       []*BatchDelete         `protobuf:"bytes,2,rep,name=deletes,proto3" json:"deletes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() { _ = "STUB: not implemented"; return }

func (x *Batch) String() string { _ = "STUB: not implemented"; return "" }

func (*Batch) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Batch) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Batch) GetPuts() []*BatchPut { _ = "STUB: not implemented"; return nil }

func (x *Batch) GetDeletes() []*BatchDelete { _ = "STUB: not implemented"; return nil }

type AtomicRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RemoveRequests [][]byte               `protobuf:"bytes,1,rep,name=remove_requests,json=removeRequests,proto3" json:"remove_requests,omitempty"`
	PutRequests    []*Element             `protobuf:"bytes,2,rep,name=put_requests,json=putRequests,proto3" json:"put_requests,omitempty"`
	PeerChainId    []byte                 `protobuf:"bytes,3,opt,name=peer_chain_id,json=peerChainId,proto3" json:"peer_chain_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AtomicRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *AtomicRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*AtomicRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *AtomicRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use AtomicRequest.ProtoReflect.Descriptor instead.
func (*AtomicRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *AtomicRequest) GetRemoveRequests() [][]byte { _ = "STUB: not implemented"; return nil }

func (x *AtomicRequest) GetPutRequests() []*Element { _ = "STUB: not implemented"; return nil }

func (x *AtomicRequest) GetPeerChainId() []byte { _ = "STUB: not implemented"; return nil }

type Element struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Traits        [][]byte               `protobuf:"bytes,3,rep,name=traits,proto3" json:"traits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Element) Reset() { _ = "STUB: not implemented"; return }

func (x *Element) String() string { _ = "STUB: not implemented"; return "" }

func (*Element) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *Element) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *Element) GetKey() []byte { _ = "STUB: not implemented"; return nil }

func (x *Element) GetValue() []byte { _ = "STUB: not implemented"; return nil }

func (x *Element) GetTraits() [][]byte { _ = "STUB: not implemented"; return nil }

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerChainId   []byte                 `protobuf:"bytes,1,opt,name=peer_chain_id,json=peerChainId,proto3" json:"peer_chain_id,omitempty"`
	Keys          [][]byte               `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *GetRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*GetRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *GetRequest) GetPeerChainId() []byte { _ = "STUB: not implemented"; return nil }

func (x *GetRequest) GetKeys() [][]byte { _ = "STUB: not implemented"; return nil }

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *GetResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*GetResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *GetResponse) GetValues() [][]byte { _ = "STUB: not implemented"; return nil }

type IndexedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerChainId   []byte                 `protobuf:"bytes,1,opt,name=peer_chain_id,json=peerChainId,proto3" json:"peer_chain_id,omitempty"`
	Traits        [][]byte               `protobuf:"bytes,2,rep,name=traits,proto3" json:"traits,omitempty"`
	StartTrait    []byte                 `protobuf:"bytes,3,opt,name=start_trait,json=startTrait,proto3" json:"start_trait,omitempty"`
	StartKey      []byte                 `protobuf:"bytes,4,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexedRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *IndexedRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*IndexedRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *IndexedRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use IndexedRequest.ProtoReflect.Descriptor instead.
func (*IndexedRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *IndexedRequest) GetPeerChainId() []byte { _ = "STUB: not implemented"; return nil }

func (x *IndexedRequest) GetTraits() [][]byte { _ = "STUB: not implemented"; return nil }

func (x *IndexedRequest) GetStartTrait() []byte { _ = "STUB: not implemented"; return nil }

func (x *IndexedRequest) GetStartKey() []byte { _ = "STUB: not implemented"; return nil }

func (x *IndexedRequest) GetLimit() int32 { _ = "STUB: not implemented"; return 0 }

type IndexedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	LastTrait     []byte                 `protobuf:"bytes,2,opt,name=last_trait,json=lastTrait,proto3" json:"last_trait,omitempty"`
	LastKey       []byte                 `protobuf:"bytes,3,opt,name=last_key,json=lastKey,proto3" json:"last_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexedResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *IndexedResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*IndexedResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *IndexedResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use IndexedResponse.ProtoReflect.Descriptor instead.
func (*IndexedResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *IndexedResponse) GetValues() [][]byte { _ = "STUB: not implemented"; return nil }

func (x *IndexedResponse) GetLastTrait() []byte { _ = "STUB: not implemented"; return nil }

func (x *IndexedResponse) GetLastKey() []byte { _ = "STUB: not implemented"; return nil }

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*AtomicRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Batches       []*Batch               `protobuf:"bytes,2,rep,name=batches,proto3" json:"batches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *ApplyRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*ApplyRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *ApplyRequest) GetRequests() []*AtomicRequest { _ = "STUB: not implemented"; return nil }

func (x *ApplyRequest) GetBatches() []*Batch { _ = "STUB: not implemented"; return nil }

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *ApplyResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*ApplyResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

var File_sharedmemory_sharedmemory_proto protoreflect.FileDescriptor

const file_sharedmemory_sharedmemory_proto_rawDesc = "" +
	"\n" +
	"\x1fsharedmemory/sharedmemory.proto\x12\fsharedmemory\"2\n" +
	"\bBatchPut\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x1f\n" +
	"\vBatchDelete\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"h\n" +
	"\x05Batch\x12*\n" +
	"\x04puts\x18\x01 \x03(\v2\x16.sharedmemory.BatchPutR\x04puts\x123\n" +
	"\adeletes\x18\x02 \x03(\v2\x19.sharedmemory.BatchDeleteR\adeletes\"\x96\x01\n" +
	"\rAtomicRequest\x12'\n" +
	"\x0fremove_requests\x18\x01 \x03(\fR\x0eremoveRequests\x128\n" +
	"\fput_requests\x18\x02 \x03(\v2\x15.sharedmemory.ElementR\vputRequests\x12\"\n" +
	"\rpeer_chain_id\x18\x03 \x01(\fR\vpeerChainId\"I\n" +
	"\aElement\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x16\n" +
	"\x06traits\x18\x03 \x03(\fR\x06traits\"D\n" +
	"\n" +
	"GetRequest\x12\"\n" +
	"\rpeer_chain_id\x18\x01 \x01(\fR\vpeerChainId\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\fR\x04keys\"%\n" +
	"\vGetResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"\xa0\x01\n" +
	"\x0eIndexedRequest\x12\"\n" +
	"\rpeer_chain_id\x18\x01 \x01(\fR\vpeerChainId\x12\x16\n" +
	"\x06traits\x18\x02 \x03(\fR\x06traits\x12\x1f\n" +
	"\vstart_trait\x18\x03 \x01(\fR\n" +
	"startTrait\x12\x1b\n" +
	"\tstart_key\x18\x04 \x01(\fR\bstartKey\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"c\n" +
	"\x0fIndexedResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\x12\x1d\n" +
	"\n" +
	"last_trait\x18\x02 \x01(\fR\tlastTrait\x12\x19\n" +
	"\blast_key\x18\x03 \x01(\fR\alastKey\"v\n" +
	"\fApplyRequest\x127\n" +
	"\brequests\x18\x01 \x03(\v2\x1b.sharedmemory.AtomicRequestR\brequests\x12-\n" +
	"\abatches\x18\x02 \x03(\v2\x13.sharedmemory.BatchR\abatches\"\x0f\n" +
	"\rApplyResponse2\xd4\x01\n" +
	"\fSharedMemory\x12:\n" +
	"\x03Get\x12\x18.sharedmemory.GetRequest\x1a\x19.sharedmemory.GetResponse\x12F\n" +
	"\aIndexed\x12\x1c.sharedmemory.IndexedRequest\x1a\x1d.sharedmemory.IndexedResponse\x12@\n" +
	"\x05Apply\x12\x1a.sharedmemory.ApplyRequest\x1a\x1b.sharedmemory.ApplyResponseB7Z5github.com/ava-labs/avalanchego/proto/pb/sharedmemoryb\x06proto3"

var (
	file_sharedmemory_sharedmemory_proto_rawDescOnce sync.Once
	file_sharedmemory_sharedmemory_proto_rawDescData []byte
)

func file_sharedmemory_sharedmemory_proto_rawDescGZIP() []byte {
	_ = "STUB: not implemented"
	return nil
}

var file_sharedmemory_sharedmemory_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_sharedmemory_sharedmemory_proto_goTypes = []any{
	(*BatchPut)(nil),        // 0: sharedmemory.BatchPut
	(*BatchDelete)(nil),     // 1: sharedmemory.BatchDelete
	(*Batch)(nil),           // 2: sharedmemory.Batch
	(*AtomicRequest)(nil),   // 3: sharedmemory.AtomicRequest
	(*Element)(nil),         // 4: sharedmemory.Element
	(*GetRequest)(nil),      // 5: sharedmemory.GetRequest
	(*GetResponse)(nil),     // 6: sharedmemory.GetResponse
	(*IndexedRequest)(nil),  // 7: sharedmemory.IndexedRequest
	(*IndexedResponse)(nil), // 8: sharedmemory.IndexedResponse
	(*ApplyRequest)(nil),    // 9: sharedmemory.ApplyRequest
	(*ApplyResponse)(nil),   // 10: sharedmemory.ApplyResponse
}
var file_sharedmemory_sharedmemory_proto_depIdxs = []int32{
	0,  // 0: sharedmemory.Batch.puts:type_name -> sharedmemory.BatchPut
	1,  // 1: sharedmemory.Batch.deletes:type_name -> sharedmemory.BatchDelete
	4,  // 2: sharedmemory.AtomicRequest.put_requests:type_name -> sharedmemory.Element
	3,  // 3: sharedmemory.ApplyRequest.requests:type_name -> sharedmemory.AtomicRequest
	2,  // 4: sharedmemory.ApplyRequest.batches:type_name -> sharedmemory.Batch
	5,  // 5: sharedmemory.SharedMemory.Get:input_type -> sharedmemory.GetRequest
	7,  // 6: sharedmemory.SharedMemory.Indexed:input_type -> sharedmemory.IndexedRequest
	9,  // 7: sharedmemory.SharedMemory.Apply:input_type -> sharedmemory.ApplyRequest
	6,  // 8: sharedmemory.SharedMemory.Get:output_type -> sharedmemory.GetResponse
	8,  // 9: sharedmemory.SharedMemory.Indexed:output_type -> sharedmemory.IndexedResponse
	10, // 10: sharedmemory.SharedMemory.Apply:output_type -> sharedmemory.ApplyResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init()                                      { file_sharedmemory_sharedmemory_proto_init() }
func file_sharedmemory_sharedmemory_proto_init() { _ = "STUB: not implemented"; return }
