// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: sharedmemory/sharedmemory.proto

package sharedmemory

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SharedMemory_Get_FullMethodName     = "/sharedmemory.SharedMemory/Get"
	SharedMemory_Indexed_FullMethodName = "/sharedmemory.SharedMemory/Indexed"
	SharedMemory_Apply_FullMethodName   = "/sharedmemory.SharedMemory/Apply"
)

// SharedMemoryClient is the client API for SharedMemory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SharedMemoryClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Indexed(ctx context.Context, in *IndexedRequest, opts ...grpc.CallOption) (*IndexedResponse, error)
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
}

type sharedMemoryClient struct {
	cc grpc.ClientConnInterface
}

func NewSharedMemoryClient(cc grpc.ClientConnInterface) SharedMemoryClient {
	_ = "STUB: not implemented"
	return *new(SharedMemoryClient)
}

func (c *sharedMemoryClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *sharedMemoryClient) Indexed(ctx context.Context, in *IndexedRequest, opts ...grpc.CallOption) (*IndexedResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *sharedMemoryClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SharedMemoryServer is the server API for SharedMemory service.
// All implementations must embed UnimplementedSharedMemoryServer
// for forward compatibility.
type SharedMemoryServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Indexed(context.Context, *IndexedRequest) (*IndexedResponse, error)
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	mustEmbedUnimplementedSharedMemoryServer()
}

// UnimplementedSharedMemoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSharedMemoryServer struct{}

func (UnimplementedSharedMemoryServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSharedMemoryServer) Indexed(context.Context, *IndexedRequest) (*IndexedResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSharedMemoryServer) Apply(context.Context, *ApplyRequest) (*ApplyResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSharedMemoryServer) mustEmbedUnimplementedSharedMemoryServer() {
	_ = "STUB: not implemented"
	return
}
func (UnimplementedSharedMemoryServer) testEmbeddedByValue() {
	_ = "STUB: not implemented"

	// UnsafeSharedMemoryServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to SharedMemoryServer will
	// result in compilation errors.
	return
}

type UnsafeSharedMemoryServer interface {
	mustEmbedUnimplementedSharedMemoryServer()
}

func RegisterSharedMemoryServer(s grpc.ServiceRegistrar, srv SharedMemoryServer) {
	_ = "STUB: not implemented"
	// If the following call pancis, it indicates UnimplementedSharedMemoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _SharedMemory_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SharedMemory_Indexed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SharedMemory_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SharedMemory_ServiceDesc is the grpc.ServiceDesc for SharedMemory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SharedMemory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sharedmemory.SharedMemory",
	HandlerType: (*SharedMemoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SharedMemory_Get_Handler,
		},
		{
			MethodName: "Indexed",
			Handler:    _SharedMemory_Indexed_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _SharedMemory_Apply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sharedmemory/sharedmemory.proto",
}
