// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: xsvm/service.proto

package xsvm

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *PingRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*PingRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PingRequest) GetMessage() string { _ = "STUB: not implemented"; return "" }

type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() { _ = "STUB: not implemented"; return }

func (x *PingReply) String() string { _ = "STUB: not implemented"; return "" }

func (*PingReply) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *PingReply) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *PingReply) GetMessage() string { _ = "STUB: not implemented"; return "" }

type StreamPingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPingRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *StreamPingRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*StreamPingRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StreamPingRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StreamPingRequest.ProtoReflect.Descriptor instead.
func (*StreamPingRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *StreamPingRequest) GetMessage() string { _ = "STUB: not implemented"; return "" }

type StreamPingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPingReply) Reset() { _ = "STUB: not implemented"; return }

func (x *StreamPingReply) String() string { _ = "STUB: not implemented"; return "" }

func (*StreamPingReply) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *StreamPingReply) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use StreamPingReply.ProtoReflect.Descriptor instead.
func (*StreamPingReply) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *StreamPingReply) GetMessage() string { _ = "STUB: not implemented"; return "" }

var File_xsvm_service_proto protoreflect.FileDescriptor

const file_xsvm_service_proto_rawDesc = "" +
	"\n" +
	"\x12xsvm/service.proto\x12\x04xsvm\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"%\n" +
	"\tPingReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"-\n" +
	"\x11StreamPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"+\n" +
	"\x0fStreamPingReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2t\n" +
	"\x04Ping\x12*\n" +
	"\x04Ping\x12\x11.xsvm.PingRequest\x1a\x0f.xsvm.PingReply\x12@\n" +
	"\n" +
	"StreamPing\x12\x17.xsvm.StreamPingRequest\x1a\x15.xsvm.StreamPingReply(\x010\x01B6Z4github.com/ava-labs/avalanchego/connectproto/pb/xsvmb\x06proto3"

var (
	file_xsvm_service_proto_rawDescOnce sync.Once
	file_xsvm_service_proto_rawDescData []byte
)

func file_xsvm_service_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_xsvm_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_xsvm_service_proto_goTypes = []any{
	(*PingRequest)(nil),       // 0: xsvm.PingRequest
	(*PingReply)(nil),         // 1: xsvm.PingReply
	(*StreamPingRequest)(nil), // 2: xsvm.StreamPingRequest
	(*StreamPingReply)(nil),   // 3: xsvm.StreamPingReply
}
var file_xsvm_service_proto_depIdxs = []int32{
	0, // 0: xsvm.Ping.Ping:input_type -> xsvm.PingRequest
	2, // 1: xsvm.Ping.StreamPing:input_type -> xsvm.StreamPingRequest
	1, // 2: xsvm.Ping.Ping:output_type -> xsvm.PingReply
	3, // 3: xsvm.Ping.StreamPing:output_type -> xsvm.StreamPingReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                         { file_xsvm_service_proto_init() }
func file_xsvm_service_proto_init() { _ = "STUB: not implemented"; return }
