// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/snow/networking/sender (interfaces: ExternalSender)
//
// Generated by this command:
//
//	mockgen -package=sendermock -destination=sendermock/external_sender.go -mock_names=ExternalSender=ExternalSender . ExternalSender
//

// Package sendermock is a generated GoMock package.
package sendermock

import (
	ids "github.com/ava-labs/avalanchego/ids"
	message "github.com/ava-labs/avalanchego/message"
	common "github.com/ava-labs/avalanchego/snow/engine/common"
	subnets "github.com/ava-labs/avalanchego/subnets"
	set "github.com/ava-labs/avalanchego/utils/set"
	gomock "go.uber.org/mock/gomock"
)

// ExternalSender is a mock of ExternalSender interface.
type ExternalSender struct {
	ctrl     *gomock.Controller
	recorder *ExternalSenderMockRecorder
	isgomock struct{}
}

// ExternalSenderMockRecorder is the mock recorder for ExternalSender.
type ExternalSenderMockRecorder struct {
	mock *ExternalSender
}

// NewExternalSender creates a new mock instance.
func NewExternalSender(ctrl *gomock.Controller) *ExternalSender {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ExternalSender) EXPECT() *ExternalSenderMockRecorder {
	_ = "STUB: not implemented"

	// Send mocks base method.
	return nil
}

func (m *ExternalSender) Send(msg *message.OutboundMessage, config common.SendConfig, subnetID ids.ID, allower subnets.Allower) set.Set[ids.NodeID] {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *ExternalSenderMockRecorder) Send(msg, config, subnetID, allower any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
