// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/codec (interfaces: Manager)
//
// Generated by this command:
//
//	mockgen -package=codecmock -destination=codecmock/manager.go -mock_names=Manager=Manager . Manager
//

// Package codecmock is a generated GoMock package.
package codecmock

import (
	codec "github.com/ava-labs/avalanchego/codec"
	gomock "go.uber.org/mock/gomock"
)

// Manager is a mock of Manager interface.
type Manager struct {
	ctrl     *gomock.Controller
	recorder *ManagerMockRecorder
	isgomock struct{}
}

// ManagerMockRecorder is the mock recorder for Manager.
type ManagerMockRecorder struct {
	mock *Manager
}

// NewManager creates a new mock instance.
func NewManager(ctrl *gomock.Controller) *Manager { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Manager) EXPECT() *ManagerMockRecorder {
	_ = "STUB: not implemented"

	// Marshal mocks base method.
	return nil
}

func (m *Manager) Marshal(version uint16, source any) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Marshal indicates an expected call of Marshal.
func (mr *ManagerMockRecorder) Marshal(version, source any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterCodec mocks base method.
func (m *Manager) RegisterCodec(version uint16, codec codec.Codec) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterCodec indicates an expected call of RegisterCodec.
func (mr *ManagerMockRecorder) RegisterCodec(version, codec any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Size mocks base method.
func (m *Manager) Size(version uint16, value any) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// Size indicates an expected call of Size.
func (mr *ManagerMockRecorder) Size(version, value any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Unmarshal mocks base method.
func (m *Manager) Unmarshal(source []byte, destination any) (uint16, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// Unmarshal indicates an expected call of Unmarshal.
func (mr *ManagerMockRecorder) Unmarshal(source, destination any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
