// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/vms (interfaces: Factory)
//
// Generated by this command:
//
//	mockgen -package=vmsmock -destination=vmsmock/factory.go -mock_names=Factory=Factory . Factory
//

// Package vmsmock is a generated GoMock package.
package vmsmock

import (
	logging "github.com/ava-labs/avalanchego/utils/logging"
	gomock "go.uber.org/mock/gomock"
)

// Factory is a mock of Factory interface.
type Factory struct {
	ctrl     *gomock.Controller
	recorder *FactoryMockRecorder
	isgomock struct{}
}

// FactoryMockRecorder is the mock recorder for Factory.
type FactoryMockRecorder struct {
	mock *Factory
}

// NewFactory creates a new mock instance.
func NewFactory(ctrl *gomock.Controller) *Factory { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Factory) EXPECT() *FactoryMockRecorder {
	_ = "STUB: not implemented"

	// New mocks base method.
	return nil
}

func (m *Factory) New(arg0 logging.Logger) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// New indicates an expected call of New.
func (mr *FactoryMockRecorder) New(arg0 any) *gomock.Call { _ = "STUB: not implemented"; return nil }
