// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package customtypes

var _ = (*headerMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (h HeaderSerializable) MarshalJSON() ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalJSON unmarshals from JSON.
func (h *HeaderSerializable) UnmarshalJSON(input []byte) error {
	_ = "STUB: not implemented"
	return nil
}
