// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: validatorstate/validator_state.proto

package validatorstate

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ValidatorState_GetMinimumHeight_FullMethodName       = "/validatorstate.ValidatorState/GetMinimumHeight"
	ValidatorState_GetCurrentHeight_FullMethodName       = "/validatorstate.ValidatorState/GetCurrentHeight"
	ValidatorState_GetSubnetID_FullMethodName            = "/validatorstate.ValidatorState/GetSubnetID"
	ValidatorState_GetWarpValidatorSets_FullMethodName   = "/validatorstate.ValidatorState/GetWarpValidatorSets"
	ValidatorState_GetValidatorSet_FullMethodName        = "/validatorstate.ValidatorState/GetValidatorSet"
	ValidatorState_GetCurrentValidatorSet_FullMethodName = "/validatorstate.ValidatorState/GetCurrentValidatorSet"
)

// ValidatorStateClient is the client API for ValidatorState service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidatorStateClient interface {
	// GetMinimumHeight returns the minimum height of the blocks in the optimal
	// proposal window.
	GetMinimumHeight(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMinimumHeightResponse, error)
	// GetCurrentHeight returns the current height of the P-chain.
	GetCurrentHeight(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCurrentHeightResponse, error)
	// GetSubnetID returns the subnetID of the provided chain.
	GetSubnetID(ctx context.Context, in *GetSubnetIDRequest, opts ...grpc.CallOption) (*GetSubnetIDResponse, error)
	// GetWarpValidatorSets returns the canonical warp validator set for all
	// subnets at the requested P-chain height. If a subnet doesn't have a valid
	// canonical warp validator set, it is omitted from the response.
	GetWarpValidatorSets(ctx context.Context, in *GetWarpValidatorSetsRequest, opts ...grpc.CallOption) (*GetWarpValidatorSetsResponse, error)
	// GetValidatorSet returns the weights of the nodeIDs for the provided
	// subnet at the requested P-chain height.
	GetValidatorSet(ctx context.Context, in *GetValidatorSetRequest, opts ...grpc.CallOption) (*GetValidatorSetResponse, error)
	// GetCurrentValidatorSet returns the validator set for the provided subnet at
	// the current P-chain height.
	GetCurrentValidatorSet(ctx context.Context, in *GetCurrentValidatorSetRequest, opts ...grpc.CallOption) (*GetCurrentValidatorSetResponse, error)
}

type validatorStateClient struct {
	cc grpc.ClientConnInterface
}

func NewValidatorStateClient(cc grpc.ClientConnInterface) ValidatorStateClient {
	_ = "STUB: not implemented"
	return *new(ValidatorStateClient)
}

func (c *validatorStateClient) GetMinimumHeight(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetMinimumHeightResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *validatorStateClient) GetCurrentHeight(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCurrentHeightResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *validatorStateClient) GetSubnetID(ctx context.Context, in *GetSubnetIDRequest, opts ...grpc.CallOption) (*GetSubnetIDResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *validatorStateClient) GetWarpValidatorSets(ctx context.Context, in *GetWarpValidatorSetsRequest, opts ...grpc.CallOption) (*GetWarpValidatorSetsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *validatorStateClient) GetValidatorSet(ctx context.Context, in *GetValidatorSetRequest, opts ...grpc.CallOption) (*GetValidatorSetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *validatorStateClient) GetCurrentValidatorSet(ctx context.Context, in *GetCurrentValidatorSetRequest, opts ...grpc.CallOption) (*GetCurrentValidatorSetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ValidatorStateServer is the server API for ValidatorState service.
// All implementations must embed UnimplementedValidatorStateServer
// for forward compatibility.
type ValidatorStateServer interface {
	// GetMinimumHeight returns the minimum height of the blocks in the optimal
	// proposal window.
	GetMinimumHeight(context.Context, *emptypb.Empty) (*GetMinimumHeightResponse, error)
	// GetCurrentHeight returns the current height of the P-chain.
	GetCurrentHeight(context.Context, *emptypb.Empty) (*GetCurrentHeightResponse, error)
	// GetSubnetID returns the subnetID of the provided chain.
	GetSubnetID(context.Context, *GetSubnetIDRequest) (*GetSubnetIDResponse, error)
	// GetWarpValidatorSets returns the canonical warp validator set for all
	// subnets at the requested P-chain height. If a subnet doesn't have a valid
	// canonical warp validator set, it is omitted from the response.
	GetWarpValidatorSets(context.Context, *GetWarpValidatorSetsRequest) (*GetWarpValidatorSetsResponse, error)
	// GetValidatorSet returns the weights of the nodeIDs for the provided
	// subnet at the requested P-chain height.
	GetValidatorSet(context.Context, *GetValidatorSetRequest) (*GetValidatorSetResponse, error)
	// GetCurrentValidatorSet returns the validator set for the provided subnet at
	// the current P-chain height.
	GetCurrentValidatorSet(context.Context, *GetCurrentValidatorSetRequest) (*GetCurrentValidatorSetResponse, error)
	mustEmbedUnimplementedValidatorStateServer()
}

// UnimplementedValidatorStateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValidatorStateServer struct{}

func (UnimplementedValidatorStateServer) GetMinimumHeight(context.Context, *emptypb.Empty) (*GetMinimumHeightResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedValidatorStateServer) GetCurrentHeight(context.Context, *emptypb.Empty) (*GetCurrentHeightResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedValidatorStateServer) GetSubnetID(context.Context, *GetSubnetIDRequest) (*GetSubnetIDResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedValidatorStateServer) GetWarpValidatorSets(context.Context, *GetWarpValidatorSetsRequest) (*GetWarpValidatorSetsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedValidatorStateServer) GetValidatorSet(context.Context, *GetValidatorSetRequest) (*GetValidatorSetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedValidatorStateServer) GetCurrentValidatorSet(context.Context, *GetCurrentValidatorSetRequest) (*GetCurrentValidatorSetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedValidatorStateServer) mustEmbedUnimplementedValidatorStateServer() {
	_ = "STUB: not implemented"
	return
}
func (UnimplementedValidatorStateServer) testEmbeddedByValue() { _ = "STUB: not implemented"; return }

// UnsafeValidatorStateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidatorStateServer will
// result in compilation errors.
type UnsafeValidatorStateServer interface {
	mustEmbedUnimplementedValidatorStateServer()
}

func RegisterValidatorStateServer(s grpc.ServiceRegistrar, srv ValidatorStateServer) {
	_ = "STUB: not implemented"
	// If the following call pancis, it indicates UnimplementedValidatorStateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	return
}

func _ValidatorState_GetMinimumHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ValidatorState_GetCurrentHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ValidatorState_GetSubnetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ValidatorState_GetWarpValidatorSets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ValidatorState_GetValidatorSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ValidatorState_GetCurrentValidatorSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ValidatorState_ServiceDesc is the grpc.ServiceDesc for ValidatorState service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValidatorState_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "validatorstate.ValidatorState",
	HandlerType: (*ValidatorStateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMinimumHeight",
			Handler:    _ValidatorState_GetMinimumHeight_Handler,
		},
		{
			MethodName: "GetCurrentHeight",
			Handler:    _ValidatorState_GetCurrentHeight_Handler,
		},
		{
			MethodName: "GetSubnetID",
			Handler:    _ValidatorState_GetSubnetID_Handler,
		},
		{
			MethodName: "GetWarpValidatorSets",
			Handler:    _ValidatorState_GetWarpValidatorSets_Handler,
		},
		{
			MethodName: "GetValidatorSet",
			Handler:    _ValidatorState_GetValidatorSet_Handler,
		},
		{
			MethodName: "GetCurrentValidatorSet",
			Handler:    _ValidatorState_GetCurrentValidatorSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "validatorstate/validator_state.proto",
}
