// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/snow/engine/avalanche/vertex (interfaces: LinearizableVM)
//
// Generated by this command:
//
//	mockgen -package=vertexmock -destination=vertexmock/linearizable_vm.go -mock_names=LinearizableVM=LinearizableVM . LinearizableVM
//

// Package vertexmock is a generated GoMock package.
package vertexmock

import (
	context "context"
	http "net/http"
	time "time"

	database "github.com/ava-labs/avalanchego/database"
	ids "github.com/ava-labs/avalanchego/ids"
	snow "github.com/ava-labs/avalanchego/snow"
	snowman "github.com/ava-labs/avalanchego/snow/consensus/snowman"
	snowstorm "github.com/ava-labs/avalanchego/snow/consensus/snowstorm"
	common "github.com/ava-labs/avalanchego/snow/engine/common"
	version "github.com/ava-labs/avalanchego/version"
	gomock "go.uber.org/mock/gomock"
)

// LinearizableVM is a mock of LinearizableVM interface.
type LinearizableVM struct {
	ctrl     *gomock.Controller
	recorder *LinearizableVMMockRecorder
	isgomock struct{}
}

// LinearizableVMMockRecorder is the mock recorder for LinearizableVM.
type LinearizableVMMockRecorder struct {
	mock *LinearizableVM
}

// NewLinearizableVM creates a new mock instance.
func NewLinearizableVM(ctrl *gomock.Controller) *LinearizableVM {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *LinearizableVM) EXPECT() *LinearizableVMMockRecorder {
	_ = "STUB: not implemented"

	// AppGossip mocks base method.
	return nil
}

func (m *LinearizableVM) AppGossip(ctx context.Context, nodeID ids.NodeID, msg []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// AppGossip indicates an expected call of AppGossip.
func (mr *LinearizableVMMockRecorder) AppGossip(ctx, nodeID, msg any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AppRequest mocks base method.
func (m *LinearizableVM) AppRequest(ctx context.Context, nodeID ids.NodeID, requestID uint32, deadline time.Time, request []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// AppRequest indicates an expected call of AppRequest.
func (mr *LinearizableVMMockRecorder) AppRequest(ctx, nodeID, requestID, deadline, request any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AppRequestFailed mocks base method.
func (m *LinearizableVM) AppRequestFailed(ctx context.Context, nodeID ids.NodeID, requestID uint32, appErr *common.AppError) error {
	_ = "STUB: not implemented"
	return nil
}

// AppRequestFailed indicates an expected call of AppRequestFailed.
func (mr *LinearizableVMMockRecorder) AppRequestFailed(ctx, nodeID, requestID, appErr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AppResponse mocks base method.
func (m *LinearizableVM) AppResponse(ctx context.Context, nodeID ids.NodeID, requestID uint32, response []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// AppResponse indicates an expected call of AppResponse.
func (mr *LinearizableVMMockRecorder) AppResponse(ctx, nodeID, requestID, response any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// BuildBlock mocks base method.
func (m *LinearizableVM) BuildBlock(arg0 context.Context) (snowman.Block, error) {
	_ = "STUB: not implemented"
	return *new(snowman.Block), nil
}

// BuildBlock indicates an expected call of BuildBlock.
func (mr *LinearizableVMMockRecorder) BuildBlock(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Connected mocks base method.
func (m *LinearizableVM) Connected(ctx context.Context, nodeID ids.NodeID, nodeVersion *version.Application) error {
	_ = "STUB: not implemented"
	return nil
}

// Connected indicates an expected call of Connected.
func (mr *LinearizableVMMockRecorder) Connected(ctx, nodeID, nodeVersion any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateHandlers mocks base method.
func (m *LinearizableVM) CreateHandlers(arg0 context.Context) (map[string]http.Handler, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateHandlers indicates an expected call of CreateHandlers.
func (mr *LinearizableVMMockRecorder) CreateHandlers(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Disconnected mocks base method.
func (m *LinearizableVM) Disconnected(ctx context.Context, nodeID ids.NodeID) error {
	_ = "STUB: not implemented"
	return nil
}

// Disconnected indicates an expected call of Disconnected.
func (mr *LinearizableVMMockRecorder) Disconnected(ctx, nodeID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBlock mocks base method.
func (m *LinearizableVM) GetBlock(ctx context.Context, blkID ids.ID) (snowman.Block, error) {
	_ = "STUB: not implemented"
	return *new(snowman.Block), nil
}

// GetBlock indicates an expected call of GetBlock.
func (mr *LinearizableVMMockRecorder) GetBlock(ctx, blkID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBlockIDAtHeight mocks base method.
func (m *LinearizableVM) GetBlockIDAtHeight(ctx context.Context, height uint64) (ids.ID, error) {
	_ = "STUB: not implemented"
	return *new(ids.ID), nil
}

// GetBlockIDAtHeight indicates an expected call of GetBlockIDAtHeight.
func (mr *LinearizableVMMockRecorder) GetBlockIDAtHeight(ctx, height any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// HealthCheck mocks base method.
func (m *LinearizableVM) HealthCheck(arg0 context.Context) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *LinearizableVMMockRecorder) HealthCheck(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Initialize mocks base method.
func (m *LinearizableVM) Initialize(ctx context.Context, chainCtx *snow.Context, db database.Database, genesisBytes, upgradeBytes, configBytes []byte, fxs []*common.Fx, appSender common.AppSender) error {
	_ = "STUB: not implemented"
	return nil
}

// Initialize indicates an expected call of Initialize.
func (mr *LinearizableVMMockRecorder) Initialize(ctx, chainCtx, db, genesisBytes, upgradeBytes, configBytes, fxs, appSender any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LastAccepted mocks base method.
func (m *LinearizableVM) LastAccepted(arg0 context.Context) (ids.ID, error) {
	_ = "STUB: not implemented"
	return *new(ids.ID), nil
}

// LastAccepted indicates an expected call of LastAccepted.
func (mr *LinearizableVMMockRecorder) LastAccepted(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Linearize mocks base method.
func (m *LinearizableVM) Linearize(ctx context.Context, stopVertexID ids.ID) error {
	_ = "STUB: not implemented"
	return nil
}

// Linearize indicates an expected call of Linearize.
func (mr *LinearizableVMMockRecorder) Linearize(ctx, stopVertexID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NewHTTPHandler mocks base method.
func (m *LinearizableVM) NewHTTPHandler(ctx context.Context) (http.Handler, error) {
	_ = "STUB: not implemented"
	return *new(http.Handler), nil
}

// NewHTTPHandler indicates an expected call of NewHTTPHandler.
func (mr *LinearizableVMMockRecorder) NewHTTPHandler(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ParseBlock mocks base method.
func (m *LinearizableVM) ParseBlock(ctx context.Context, blockBytes []byte) (snowman.Block, error) {
	_ = "STUB: not implemented"
	return *new(snowman.Block), nil
}

// ParseBlock indicates an expected call of ParseBlock.
func (mr *LinearizableVMMockRecorder) ParseBlock(ctx, blockBytes any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ParseTx mocks base method.
func (m *LinearizableVM) ParseTx(ctx context.Context, txBytes []byte) (snowstorm.Tx, error) {
	_ = "STUB: not implemented"
	return *new(snowstorm.Tx), nil
}

// ParseTx indicates an expected call of ParseTx.
func (mr *LinearizableVMMockRecorder) ParseTx(ctx, txBytes any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetPreference mocks base method.
func (m *LinearizableVM) SetPreference(ctx context.Context, blkID ids.ID) error {
	_ = "STUB: not implemented"
	return nil
}

// SetPreference indicates an expected call of SetPreference.
func (mr *LinearizableVMMockRecorder) SetPreference(ctx, blkID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetState mocks base method.
func (m *LinearizableVM) SetState(ctx context.Context, state snow.State) error {
	_ = "STUB: not implemented"
	return nil
}

// SetState indicates an expected call of SetState.
func (mr *LinearizableVMMockRecorder) SetState(ctx, state any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Shutdown mocks base method.
func (m *LinearizableVM) Shutdown(arg0 context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// Shutdown indicates an expected call of Shutdown.
func (mr *LinearizableVMMockRecorder) Shutdown(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Version mocks base method.
func (m *LinearizableVM) Version(arg0 context.Context) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// Version indicates an expected call of Version.
func (mr *LinearizableVMMockRecorder) Version(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WaitForEvent mocks base method.
func (m *LinearizableVM) WaitForEvent(ctx context.Context) (common.Message, error) {
	_ = "STUB: not implemented"
	return *new(common.Message), nil
}

// WaitForEvent indicates an expected call of WaitForEvent.
func (mr *LinearizableVMMockRecorder) WaitForEvent(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
