// Code generated by MockGen. DO NOT EDIT.
// Source: signer.go
//
// Generated by this command:
//
//	mockgen -package=signermock -source=signer.go -destination=signermock/signer.go -mock_names=Signer=Signer
//

// Package signermock is a generated GoMock package.
package signermock

import (
	bls "github.com/ava-labs/avalanchego/utils/crypto/bls"
	gomock "go.uber.org/mock/gomock"
)

// Signer is a mock of Signer interface.
type Signer struct {
	ctrl     *gomock.Controller
	recorder *SignerMockRecorder
	isgomock struct{}
}

// SignerMockRecorder is the mock recorder for Signer.
type SignerMockRecorder struct {
	mock *Signer
}

// NewSigner creates a new mock instance.
func NewSigner(ctrl *gomock.Controller) *Signer { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Signer) EXPECT() *SignerMockRecorder {
	_ = "STUB: not implemented"

	// Key mocks base method.
	return nil
}

func (m *Signer) Key() *bls.PublicKey { _ = "STUB: not implemented"; return nil }

// Key indicates an expected call of Key.
func (mr *SignerMockRecorder) Key() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Verify mocks base method.
func (m *Signer) Verify() error { _ = "STUB: not implemented"; return nil }

// Verify indicates an expected call of Verify.
func (mr *SignerMockRecorder) Verify() *gomock.Call { _ = "STUB: not implemented"; return nil }
