// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/vms/components/verify (interfaces: Verifiable)
//
// Generated by this command:
//
//	mockgen -package=verifymock -destination=verifymock/verifiable.go -mock_names=Verifiable=Verifiable . Verifiable
//

// Package verifymock is a generated GoMock package.
package verifymock

import (
	gomock "go.uber.org/mock/gomock"
)

// Verifiable is a mock of Verifiable interface.
type Verifiable struct {
	ctrl     *gomock.Controller
	recorder *VerifiableMockRecorder
	isgomock struct{}
}

// VerifiableMockRecorder is the mock recorder for Verifiable.
type VerifiableMockRecorder struct {
	mock *Verifiable
}

// NewVerifiable creates a new mock instance.
func NewVerifiable(ctrl *gomock.Controller) *Verifiable { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Verifiable) EXPECT() *VerifiableMockRecorder {
	_ = "STUB: not implemented"

	// Verify mocks base method.
	return nil
}

func (m *Verifiable) Verify() error { _ = "STUB: not implemented"; return nil }

// Verify indicates an expected call of Verify.
func (mr *VerifiableMockRecorder) Verify() *gomock.Call { _ = "STUB: not implemented"; return nil }
