// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/vms/proposervm/proposer (interfaces: Windower)
//
// Generated by this command:
//
//	mockgen -package=proposermock -destination=proposermock/windower.go -mock_names=Windower=Windower . Windower
//

// Package proposermock is a generated GoMock package.
package proposermock

import (
	context "context"
	time "time"

	ids "github.com/ava-labs/avalanchego/ids"
	gomock "go.uber.org/mock/gomock"
)

// Windower is a mock of Windower interface.
type Windower struct {
	ctrl     *gomock.Controller
	recorder *WindowerMockRecorder
	isgomock struct{}
}

// WindowerMockRecorder is the mock recorder for Windower.
type WindowerMockRecorder struct {
	mock *Windower
}

// NewWindower creates a new mock instance.
func NewWindower(ctrl *gomock.Controller) *Windower { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Windower) EXPECT() *WindowerMockRecorder {
	_ = "STUB: not implemented"

	// Delay mocks base method.
	return nil
}

func (m *Windower) Delay(ctx context.Context, blockHeight, pChainHeight uint64, validatorID ids.NodeID, maxWindows int) (time.Duration, error) {
	_ = "STUB: not implemented"
	return *new(time.Duration), nil
}

// Delay indicates an expected call of Delay.
func (mr *WindowerMockRecorder) Delay(ctx, blockHeight, pChainHeight, validatorID, maxWindows any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ExpectedProposer mocks base method.
func (m *Windower) ExpectedProposer(ctx context.Context, blockHeight, pChainHeight, slot uint64) (ids.NodeID, error) {
	_ = "STUB: not implemented"
	return *new(ids.NodeID), nil
}

// ExpectedProposer indicates an expected call of ExpectedProposer.
func (mr *WindowerMockRecorder) ExpectedProposer(ctx, blockHeight, pChainHeight, slot any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MinDelayForProposer mocks base method.
func (m *Windower) MinDelayForProposer(ctx context.Context, blockHeight, pChainHeight uint64, nodeID ids.NodeID, startSlot uint64) (time.Duration, error) {
	_ = "STUB: not implemented"
	return *new(time.Duration), nil
}

// MinDelayForProposer indicates an expected call of MinDelayForProposer.
func (mr *WindowerMockRecorder) MinDelayForProposer(ctx, blockHeight, pChainHeight, nodeID, startSlot any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Proposers mocks base method.
func (m *Windower) Proposers(ctx context.Context, blockHeight, pChainHeight uint64, maxWindows int) ([]ids.NodeID, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Proposers indicates an expected call of Proposers.
func (mr *WindowerMockRecorder) Proposers(ctx, blockHeight, pChainHeight, maxWindows any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
