// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/vms/avm/state (interfaces: Chain)
//
// Generated by this command:
//
//	mockgen -package=statemock -destination=statemock/chain.go -mock_names=Chain=Chain . Chain
//

// Package statemock is a generated GoMock package.
package statemock

import (
	time "time"

	ids "github.com/ava-labs/avalanchego/ids"
	block "github.com/ava-labs/avalanchego/vms/avm/block"
	txs "github.com/ava-labs/avalanchego/vms/avm/txs"
	avax "github.com/ava-labs/avalanchego/vms/components/avax"
	gomock "go.uber.org/mock/gomock"
)

// Chain is a mock of Chain interface.
type Chain struct {
	ctrl     *gomock.Controller
	recorder *ChainMockRecorder
	isgomock struct{}
}

// ChainMockRecorder is the mock recorder for Chain.
type ChainMockRecorder struct {
	mock *Chain
}

// NewChain creates a new mock instance.
func NewChain(ctrl *gomock.Controller) *Chain { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Chain) EXPECT() *ChainMockRecorder {
	_ = "STUB: not implemented"

	// AddBlock mocks base method.
	return nil
}

func (m *Chain) AddBlock(block block.Block) { _ = "STUB: not implemented"; return }

// AddBlock indicates an expected call of AddBlock.
func (mr *ChainMockRecorder) AddBlock(block any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AddTx mocks base method.
func (m *Chain) AddTx(tx *txs.Tx) { _ = "STUB: not implemented"; return }

// AddTx indicates an expected call of AddTx.
func (mr *ChainMockRecorder) AddTx(tx any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// AddUTXO mocks base method.
func (m *Chain) AddUTXO(utxo *avax.UTXO) { _ = "STUB: not implemented"; return }

// AddUTXO indicates an expected call of AddUTXO.
func (mr *ChainMockRecorder) AddUTXO(utxo any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// DeleteUTXO mocks base method.
func (m *Chain) DeleteUTXO(utxoID ids.ID) { _ = "STUB: not implemented"; return }

// DeleteUTXO indicates an expected call of DeleteUTXO.
func (mr *ChainMockRecorder) DeleteUTXO(utxoID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBlock mocks base method.
func (m *Chain) GetBlock(blkID ids.ID) (block.Block, error) {
	_ = "STUB: not implemented"
	return *new(block.Block), nil
}

// GetBlock indicates an expected call of GetBlock.
func (mr *ChainMockRecorder) GetBlock(blkID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBlockIDAtHeight mocks base method.
func (m *Chain) GetBlockIDAtHeight(height uint64) (ids.ID, error) {
	_ = "STUB: not implemented"
	return *new(ids.ID), nil
}

// GetBlockIDAtHeight indicates an expected call of GetBlockIDAtHeight.
func (mr *ChainMockRecorder) GetBlockIDAtHeight(height any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLastAccepted mocks base method.
func (m *Chain) GetLastAccepted() ids.ID { _ = "STUB: not implemented"; return *new(ids.ID) }

// GetLastAccepted indicates an expected call of GetLastAccepted.
func (mr *ChainMockRecorder) GetLastAccepted() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetTimestamp mocks base method.
func (m *Chain) GetTimestamp() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

// GetTimestamp indicates an expected call of GetTimestamp.
func (mr *ChainMockRecorder) GetTimestamp() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetTx mocks base method.
func (m *Chain) GetTx(txID ids.ID) (*txs.Tx, error) { _ = "STUB: not implemented"; return nil, nil }

// GetTx indicates an expected call of GetTx.
func (mr *ChainMockRecorder) GetTx(txID any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetUTXO mocks base method.
func (m *Chain) GetUTXO(utxoID ids.ID) (*avax.UTXO, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUTXO indicates an expected call of GetUTXO.
func (mr *ChainMockRecorder) GetUTXO(utxoID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetLastAccepted mocks base method.
func (m *Chain) SetLastAccepted(blkID ids.ID) { _ = "STUB: not implemented"; return }

// SetLastAccepted indicates an expected call of SetLastAccepted.
func (mr *ChainMockRecorder) SetLastAccepted(blkID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTimestamp mocks base method.
func (m *Chain) SetTimestamp(t time.Time) { _ = "STUB: not implemented"; return }

// SetTimestamp indicates an expected call of SetTimestamp.
func (mr *ChainMockRecorder) SetTimestamp(t any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
