// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/vms/avm/state (interfaces: Diff)
//
// Generated by this command:
//
//	mockgen -package=statemock -destination=statemock/diff.go -mock_names=Diff=Diff . Diff
//

// Package statemock is a generated GoMock package.
package statemock

import (
	time "time"

	ids "github.com/ava-labs/avalanchego/ids"
	block "github.com/ava-labs/avalanchego/vms/avm/block"
	state "github.com/ava-labs/avalanchego/vms/avm/state"
	txs "github.com/ava-labs/avalanchego/vms/avm/txs"
	avax "github.com/ava-labs/avalanchego/vms/components/avax"
	gomock "go.uber.org/mock/gomock"
)

// Diff is a mock of Diff interface.
type Diff struct {
	ctrl     *gomock.Controller
	recorder *DiffMockRecorder
	isgomock struct{}
}

// DiffMockRecorder is the mock recorder for Diff.
type DiffMockRecorder struct {
	mock *Diff
}

// NewDiff creates a new mock instance.
func NewDiff(ctrl *gomock.Controller) *Diff { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Diff) EXPECT() *DiffMockRecorder {
	_ = "STUB: not implemented"

	// AddBlock mocks base method.
	return nil
}

func (m *Diff) AddBlock(block block.Block) { _ = "STUB: not implemented"; return }

// AddBlock indicates an expected call of AddBlock.
func (mr *DiffMockRecorder) AddBlock(block any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// AddTx mocks base method.
func (m *Diff) AddTx(tx *txs.Tx) { _ = "STUB: not implemented"; return }

// AddTx indicates an expected call of AddTx.
func (mr *DiffMockRecorder) AddTx(tx any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// AddUTXO mocks base method.
func (m *Diff) AddUTXO(utxo *avax.UTXO) { _ = "STUB: not implemented"; return }

// AddUTXO indicates an expected call of AddUTXO.
func (mr *DiffMockRecorder) AddUTXO(utxo any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// Apply mocks base method.
func (m *Diff) Apply(arg0 state.Chain) { _ = "STUB: not implemented"; return }

// Apply indicates an expected call of Apply.
func (mr *DiffMockRecorder) Apply(arg0 any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// DeleteUTXO mocks base method.
func (m *Diff) DeleteUTXO(utxoID ids.ID) { _ = "STUB: not implemented"; return }

// DeleteUTXO indicates an expected call of DeleteUTXO.
func (mr *DiffMockRecorder) DeleteUTXO(utxoID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBlock mocks base method.
func (m *Diff) GetBlock(blkID ids.ID) (block.Block, error) {
	_ = "STUB: not implemented"
	return *new(block.Block), nil
}

// GetBlock indicates an expected call of GetBlock.
func (mr *DiffMockRecorder) GetBlock(blkID any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetBlockIDAtHeight mocks base method.
func (m *Diff) GetBlockIDAtHeight(height uint64) (ids.ID, error) {
	_ = "STUB: not implemented"
	return *new(ids.ID), nil
}

// GetBlockIDAtHeight indicates an expected call of GetBlockIDAtHeight.
func (mr *DiffMockRecorder) GetBlockIDAtHeight(height any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLastAccepted mocks base method.
func (m *Diff) GetLastAccepted() ids.ID { _ = "STUB: not implemented"; return *new(ids.ID) }

// GetLastAccepted indicates an expected call of GetLastAccepted.
func (mr *DiffMockRecorder) GetLastAccepted() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetTimestamp mocks base method.
func (m *Diff) GetTimestamp() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

// GetTimestamp indicates an expected call of GetTimestamp.
func (mr *DiffMockRecorder) GetTimestamp() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetTx mocks base method.
func (m *Diff) GetTx(txID ids.ID) (*txs.Tx, error) { _ = "STUB: not implemented"; return nil, nil }

// GetTx indicates an expected call of GetTx.
func (mr *DiffMockRecorder) GetTx(txID any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetUTXO mocks base method.
func (m *Diff) GetUTXO(utxoID ids.ID) (*avax.UTXO, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUTXO indicates an expected call of GetUTXO.
func (mr *DiffMockRecorder) GetUTXO(utxoID any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// SetLastAccepted mocks base method.
func (m *Diff) SetLastAccepted(blkID ids.ID) { _ = "STUB: not implemented"; return }

// SetLastAccepted indicates an expected call of SetLastAccepted.
func (mr *DiffMockRecorder) SetLastAccepted(blkID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTimestamp mocks base method.
func (m *Diff) SetTimestamp(t time.Time) { _ = "STUB: not implemented"; return }

// SetTimestamp indicates an expected call of SetTimestamp.
func (mr *DiffMockRecorder) SetTimestamp(t any) *gomock.Call { _ = "STUB: not implemented"; return nil }
