// Copyright (C) 2019, Ava Labs, Inc. All rights reserved.
// See the file LICENSE for licensing terms.

// Code generated
// This file is a generated precompile contract config with stubbed abstract functions.
// The file is generated by a template. Please inspect every code and comment in this file before use.

package feemanager

import (
	"math/big"

	"github.com/ava-labs/avalanchego/graft/subnet-evm/commontype"
	"github.com/ava-labs/avalanchego/graft/subnet-evm/precompile/contract"
	"github.com/ava-labs/libevm/common"
)

// FeeConfigChangedEventGasCost is the gas cost of a FeeConfigChanged event.
// It is the base gas cost + the gas cost of the topics (signature, sender)
// and the gas cost of the non-indexed data len(oldConfig) + len(newConfig).
const FeeConfigChangedEventGasCost = GetFeeConfigGasCost + contract.LogGas + contract.LogTopicGas*2 + 2*(feeConfigInputLen)*contract.LogDataGas

// changeFeeConfigEventData represents a ChangeFeeConfig non-indexed event data raised by the contract.
// This represents a different struct than commontype.FeeConfig, because in the contract TargetBlockRate is defined as uint256.
// uint256 must be unpacked into *big.Int
type changeFeeConfigEventData struct {
	GasLimit                 *big.Int
	TargetBlockRate          *big.Int
	MinBaseFee               *big.Int
	TargetGas                *big.Int
	BaseFeeChangeDenominator *big.Int
	MinBlockGasCost          *big.Int
	MaxBlockGasCost          *big.Int
	BlockGasCostStep         *big.Int
}

// PackFeeConfigChangedEvent packs the event into the appropriate arguments for changeFeeConfig.
// It returns topic hashes and the encoded non-indexed data.
func PackFeeConfigChangedEvent(sender common.Address, oldConfig commontype.FeeConfig, newConfig commontype.FeeConfig) ([]common.Hash, []byte, error) {
	_ = "STUB: not implemented"
	return nil, nil, nil
}

// UnpackFeeConfigChangedEventData attempts to unpack non-indexed [dataBytes].
func UnpackFeeConfigChangedEventData(dataBytes []byte) (commontype.FeeConfig, commontype.FeeConfig, error) {
	_ = "STUB: not implemented"
	return *new(commontype.FeeConfig), *new(commontype.FeeConfig), nil
}

func convertFromCommonConfig(config commontype.FeeConfig) changeFeeConfigEventData {
	_ = "STUB: not implemented"
	return *new(changeFeeConfigEventData)
}

func convertToCommonConfig(config changeFeeConfigEventData) commontype.FeeConfig {
	_ = "STUB: not implemented"
	return *new(commontype.FeeConfig)
}
