// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/vms/platformvm/fx (interfaces: Fx)
//
// Generated by this command:
//
//	mockgen -package=fxmock -destination=fxmock/fx.go -mock_names=Fx=Fx . Fx
//

// Package fxmock is a generated GoMock package.
package fxmock

import (
	gomock "go.uber.org/mock/gomock"
)

// Fx is a mock of Fx interface.
type Fx struct {
	ctrl     *gomock.Controller
	recorder *FxMockRecorder
	isgomock struct{}
}

// FxMockRecorder is the mock recorder for Fx.
type FxMockRecorder struct {
	mock *Fx
}

// NewFx creates a new mock instance.
func NewFx(ctrl *gomock.Controller) *Fx { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Fx) EXPECT() *FxMockRecorder {
	_ = "STUB: not implemented"

	// Bootstrapped mocks base method.
	return nil
}

func (m *Fx) Bootstrapped() error { _ = "STUB: not implemented"; return nil }

// Bootstrapped indicates an expected call of Bootstrapped.
func (mr *FxMockRecorder) Bootstrapped() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Bootstrapping mocks base method.
func (m *Fx) Bootstrapping() error { _ = "STUB: not implemented"; return nil }

// Bootstrapping indicates an expected call of Bootstrapping.
func (mr *FxMockRecorder) Bootstrapping() *gomock.Call { _ = "STUB: not implemented"; return nil }

// CreateOutput mocks base method.
func (m *Fx) CreateOutput(amount uint64, controlGroup any) (any, error) {
	_ = "STUB: not implemented"
	return *new(any), nil
}

// CreateOutput indicates an expected call of CreateOutput.
func (mr *FxMockRecorder) CreateOutput(amount, controlGroup any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Initialize mocks base method.
func (m *Fx) Initialize(vm any) error { _ = "STUB: not implemented"; return nil }

// Initialize indicates an expected call of Initialize.
func (mr *FxMockRecorder) Initialize(vm any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// VerifyPermission mocks base method.
func (m *Fx) VerifyPermission(tx, in, cred, controlGroup any) error {
	_ = "STUB: not implemented"
	return nil
}

// VerifyPermission indicates an expected call of VerifyPermission.
func (mr *FxMockRecorder) VerifyPermission(tx, in, cred, controlGroup any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// VerifyTransfer mocks base method.
func (m *Fx) VerifyTransfer(tx, in, cred, utxo any) error { _ = "STUB: not implemented"; return nil }

// VerifyTransfer indicates an expected call of VerifyTransfer.
func (mr *FxMockRecorder) VerifyTransfer(tx, in, cred, utxo any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
