// Code generated by MockGen and manually edited.
// Source: github.com/ava-labs/avalanchego/vms/platformvm/fx (interfaces: Owner)
//
// Generated by this command:
//
//	mockgen -package=fxmock -destination=vms/platformvm/fx/fxmock/owner.go -mock_names=Owner=Owner github.com/ava-labs/avalanchego/vms/platformvm/fx Owner
//

// Package fxmock is a generated GoMock package.
package fxmock

import (
	snow "github.com/ava-labs/avalanchego/snow"
	verify "github.com/ava-labs/avalanchego/vms/components/verify"
	gomock "go.uber.org/mock/gomock"
)

// Owner is a mock of Owner interface.
type Owner struct {
	verify.IsNotState

	ctrl     *gomock.Controller
	recorder *OwnerMockRecorder
}

// OwnerMockRecorder is the mock recorder for Owner.
type OwnerMockRecorder struct {
	mock *Owner
}

// NewOwner creates a new mock instance.
func NewOwner(ctrl *gomock.Controller) *Owner { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Owner) EXPECT() *OwnerMockRecorder {
	_ = "STUB: not implemented"

	// InitCtx mocks base method.
	return nil
}

func (m *Owner) InitCtx(arg0 *snow.Context) { _ = "STUB: not implemented"; return }

// InitCtx indicates an expected call of InitCtx.
func (mr *OwnerMockRecorder) InitCtx(arg0 any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// Verify mocks base method.
func (m *Owner) Verify() error { _ = "STUB: not implemented"; return nil }

// Verify indicates an expected call of Verify.
func (mr *OwnerMockRecorder) Verify() *gomock.Call { _ = "STUB: not implemented"; return nil }

// isState mocks base method.
func (m *Owner) isState() error { _ = "STUB: not implemented"; return nil }

// isState indicates an expected call of isState.
func (mr *OwnerMockRecorder) isState() *gomock.Call { _ = "STUB: not implemented"; return nil }
