// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ava-labs/avalanchego/snow/validators (interfaces: State)
//
// Generated by this command:
//
//	mockgen -package=validatorsmock -destination=validatorsmock/state.go -mock_names=State=State . State
//

// Package validatorsmock is a generated GoMock package.
package validatorsmock

import (
	context "context"

	ids "github.com/ava-labs/avalanchego/ids"
	validators "github.com/ava-labs/avalanchego/snow/validators"
	gomock "go.uber.org/mock/gomock"
)

// State is a mock of State interface.
type State struct {
	ctrl     *gomock.Controller
	recorder *StateMockRecorder
	isgomock struct{}
}

// StateMockRecorder is the mock recorder for State.
type StateMockRecorder struct {
	mock *State
}

// NewState creates a new mock instance.
func NewState(ctrl *gomock.Controller) *State { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *State) EXPECT() *StateMockRecorder {
	_ = "STUB: not implemented"

	// GetCurrentHeight mocks base method.
	return nil
}

func (m *State) GetCurrentHeight(arg0 context.Context) (uint64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// GetCurrentHeight indicates an expected call of GetCurrentHeight.
func (mr *StateMockRecorder) GetCurrentHeight(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetCurrentValidatorSet mocks base method.
func (m *State) GetCurrentValidatorSet(ctx context.Context, subnetID ids.ID) (map[ids.ID]*validators.GetCurrentValidatorOutput, uint64, error) {
	_ = "STUB: not implemented"
	return nil, 0, nil
}

// GetCurrentValidatorSet indicates an expected call of GetCurrentValidatorSet.
func (mr *StateMockRecorder) GetCurrentValidatorSet(ctx, subnetID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetMinimumHeight mocks base method.
func (m *State) GetMinimumHeight(arg0 context.Context) (uint64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// GetMinimumHeight indicates an expected call of GetMinimumHeight.
func (mr *StateMockRecorder) GetMinimumHeight(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSubnetID mocks base method.
func (m *State) GetSubnetID(ctx context.Context, chainID ids.ID) (ids.ID, error) {
	_ = "STUB: not implemented"
	return *new(ids.ID), nil
}

// GetSubnetID indicates an expected call of GetSubnetID.
func (mr *StateMockRecorder) GetSubnetID(ctx, chainID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetValidatorSet mocks base method.
func (m *State) GetValidatorSet(ctx context.Context, height uint64, subnetID ids.ID) (map[ids.NodeID]*validators.GetValidatorOutput, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetValidatorSet indicates an expected call of GetValidatorSet.
func (mr *StateMockRecorder) GetValidatorSet(ctx, height, subnetID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetWarpValidatorSets mocks base method.
func (m *State) GetWarpValidatorSets(ctx context.Context, height uint64) (map[ids.ID]validators.WarpSet, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetWarpValidatorSets indicates an expected call of GetWarpValidatorSets.
func (mr *StateMockRecorder) GetWarpValidatorSets(ctx, height any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
